# Cleaning Used Cars
## A pandas / numpy project

The aim of this project is to clean a webscraped dataset containing info on used cars, sold on Ebay. The dataset contains 50,000 datapoints and [can be found on Kaggle](https://www.kaggle.com/orgesleka/used-cars-database/data).

It must be noted that the dataset has been muddied by Dataquest.io for data cleaning practice purposes.

The cleaned dataset can then be used for analytics or machine learning prediction purposes. The aim is to use this dataset for a model predicting the price you can get for your car (separate project).

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
from matplotlib import pyplot as plt
%matplotlib inline

autos = pd.read_csv('autos.csv', encoding='latin1')

### Data exploration

Let's start with examining the dataset to get an idea of what we are working with and where to start cleaning.

In [2]:
autos

,dateCrawled,name,seller,offerType,price,abtest,vehicleType,yearOfRegistration,gearbox,powerPS,model,odometer,monthOfRegistration,fuelType,brand,notRepairedDamage,dateCreated,nrOfPictures,postalCode,lastSeen
0,2016-03-26 17:47:46,Peugeot_807_160_NAVTECH_ON_BOARD,privat,Angebot,"$5,000",control,bus,2004,manuell,158,andere,"150,000km",3,lpg,peugeot,nein,2016-03-26 00:00:00,0,79588,2016-04-06 06:45:54
1,2016-04-04 13:38:56,BMW_740i_4_4_Liter_HAMANN_UMBAU_Mega_Optik,privat,Angebot,"$8,500",control,limousine,1997,automatik,286,7er,"150,000km",6,benzin,bmw,nein,2016-04-04 00:00:00,0,71034,2016-04-06 14:45:08
2,2016-03-26 18:57:24,Volkswagen_Golf_1.6_United,privat,Angebot,"$8,990",test,limousine,2009,manuell,102,golf,"70,000km",7,benzin,volkswagen,nein,2016-03-26 00:00:00,0,35394,2016-04-06 20:15:37
3,2016-03-12 16:58:10,Smart_smart_fortwo_coupe_softouch/F1/Klima/Pan...,privat,Angebot,"$4,350",control,kleinwagen,2007,automatik,71,fortwo,"70,000km",6,benzin,smart,nein,2016-03-12 00:00:00,0,33729,2016-03-15 03:16:28
4,2016-04-01 14:38:50,Ford_Focus_1_6_Benzin_TÃœV_neu_ist_sehr_gepfleg...,privat,Angebot,"$1,350",test,kombi,2003,manuell,0,focus,"150,000km",7,benzin,ford,nein,2016-04-01 00:00:00,0,39218,2016-04-01 14:38:50
5,2016-03-21 13:47:45,Chrysler_Grand_Voyager_2.8_CRD_Aut.Limited_Sto...,privat,Angebot,"$7,900",test,bus,2006,automatik,150,voyager,"150,000km",4,diesel,chrysler,NaN,2016-03-21 00:00:00,0,22962,2016-04-06 09:45:21
6,2016-03-20 17:55:21,VW_Golf_III_GT_Special_Electronic_Green_Metall...,privat,Angebot,$300,test,limousine,1995,manuell,90,golf,"150,000km",8,benzin,volkswagen,NaN,2016-03-20 00:00:00,0,31535,2016-03-23 02:48:59
7,2016-03-16 18:55:19,Golf_IV_1.9_TDI_90PS,privat,Angebot,"$1,990",control,limousine,1998,manuell,90,golf,"150,000km",12,diesel,volkswagen,nein,2016-03-16 00:00:00,0,53474,2016-04-07 03:17:32
8,2016-03-22 16:51:34,Seat_Arosa,privat,Angebot,$250,test,NaN,2000,manuell,0,arosa,"150,000km",10,NaN,seat,nein,2016-03-22 00:00:00,0,7426,2016-03-26 18:18:10
9,2016-03-16 13:47:02,Renault_Megane_Scenic_1.6e_RT_Klimaanlage,privat,Angebot,$590,control,bus,1997,manuell,90,megane,"150,000km",7,benzin,renault,nein,2016-03-16 00:00:00,0,15749,2016-04-06 10:46:35
10,2016-03-15 01:41:36,VW_Golf_Tuning_in_siber/grau,privat,Angebot,$999,test,NaN,2017,manuell,90,NaN,"150,000km",4,benzin,volkswagen,nein,2016-03-14 00:00:00,0,86157,2016-04-07 03:16:21
11,2016-03-16 18:45:34,Mercedes_A140_Motorschaden,privat,Angebot,$350,control,NaN,2000,NaN,0,NaN,"150,000km",0,benzin,mercedes_benz,NaN,2016-03-16 00:00:00,0,17498,2016-03-16 18:45:34
12,2016-03-31 19:48:22,Smart_smart_fortwo_coupe_softouch_pure_MHD_Pan...,privat,Angebot,"$5,299",control,kleinwagen,2010,automatik,71,fortwo,"50,000km",9,benzin,smart,nein,2016-03-31 00:00:00,0,34590,2016-04-06 14:17:52
13,2016-03-23 10:48:32,Audi_A3_1.6_tuning,privat,Angebot,"$1,350",control,limousine,1999,manuell,101,a3,"150,000km",11,benzin,audi,nein,2016-03-23 00:00:00,0,12043,2016-04-01 14:17:13
14,2016-03-23 11:50:46,Renault_Clio_3__Dynamique_1.2__16_V;_viele_Ver...,privat,Angebot,"$3,999",test,kleinwagen,2007,manuell,75,clio,"150,000km",9,benzin,renault,NaN,2016-03-23 00:00:00,0,81737,2016-04-01 15:46:47
15,2016-04-01 12:06:20,Corvette_C3_Coupe_T_Top_Crossfire_Injection,privat,Angebot,"$18,900",test,coupe,1982,automatik,203,NaN,"80,000km",6,benzin,sonstige_autos,nein,2016-04-01 00:00:00,0,61276,2016-04-02 21:10:48
16,2016-03-16 14:59:02,Opel_Vectra_B_Kombi,privat,Angebot,$350,test,kombi,1999,manuell,101,vectra,"150,000km",5,benzin,opel,nein,2016-03-16 00:00:00,0,57299,2016-03-18 05:29:37
17,2016-03-29 11:46:22,Volkswagen_Scirocco_2_G60,privat,Angebot,"$5,500",test,coupe,1990,manuell,205,scirocco,"150,000km",6,benzin,volkswagen,nein,2016-03-29 00:00:00,0,74821,2016-04-05 20:46:26
18,2016-03-26 19:57:44,Verkaufen_mein_bmw_e36_320_i_touring,privat,Angebot,$300,control,bus,1995,manuell,150,3er,"150,000km",0,benzin,bmw,NaN,2016-03-26 00:00:00,0,54329,2016-04-02 12:16:41
19,2016-03-17 13:36:21,mazda_tribute_2.0_mit_gas_und_tuev_neu_2018,privat,Angebot,"$4,150",control,suv,2004,manuell,124,andere,"150,000km",2,lpg,mazda,nein,2016-03-17 00:00:00,0,40878,2016-03-17 14:45:58
20,2016-03-05 19:57:31,Audi_A4_Avant_1.9_TDI_*6_Gang*AHK*Klimatronik*...,privat,Angebot,"$3,500",test,kombi,2003,manuell,131,a4,"150,000km",5,diesel,audi,NaN,2016-03-05 00:00:00,0,53913,2016-03-07 05:46:46
21,2016-03-06 19:07:10,Porsche_911_Carrera_4S_Cabrio,privat,Angebot,"$41,500",test,cabrio,2004,manuell,320,911,"150,000km",4,benzin,porsche,nein,2016-03-06 00:00:00,0,65428,2016-04-05 23:46:19
22,2016-03-28 20:50:54,MINI_Cooper_S_Cabrio,privat,Angebot,"$25,450",control,cabrio,2015,manuell,184,cooper,"10,000km",1,benzin,mini,nein,2016-03-28 00:00:00,0,44789,2016-04-01 06:45:30
23,2016-03-10 19:55:34,Peugeot_Boxer_2_2_HDi_120_Ps_9_Sitzer_inkl_Klima,privat,Angebot,"$7,999",control,bus,2010,manuell,120,NaN,"150,000km",2,diesel,peugeot,nein,2016-03-10 00:00:00,0,30900,2016-03-17 08:45:17
24,2016-04-03 11:57:02,BMW_535i_xDrive_Sport_Aut.,privat,Angebot,"$48,500",control,limousine,2014,automatik,306,5er,"30,000km",12,benzin,bmw,nein,2016-04-03 00:00:00,0,22547,2016-04-07 13:16:50
25,2016-03-21 21:56:18,Ford_escort_kombi_an_bastler_mit_ghia_ausstattung,privat,Angebot,$90,control,kombi,1996,manuell,116,NaN,"150,000km",4,benzin,ford,ja,2016-03-21 00:00:00,0,27574,2016-04-01 05:16:49
26,2016-04-03 22:46:28,Volkswagen_Polo_Fox,privat,Angebot,$777,control,kleinwagen,1992,manuell,54,polo,"125,000km",2,benzin,volkswagen,nein,2016-04-03 00:00:00,0,38110,2016-04-05 23:46:48
27,2016-03-27 18:45:01,Hat_einer_Ahnung_mit_Ford_Galaxy_HILFE,privat,Angebot,$0,control,NaN,2005,NaN,0,NaN,"150,000km",0,NaN,ford,NaN,2016-03-27 00:00:00,0,66701,2016-03-27 18:45:01
28,2016-03-19 21:56:19,MINI_Cooper_D,privat,Angebot,"$5,250",control,kleinwagen,2007,manuell,110,cooper,"150,000km",7,diesel,mini,ja,2016-03-19 00:00:00,0,15745,2016-04-07 14:58:48
29,2016-04-02 12:45:44,Mercedes_Benz_E_320_T_CDI_Avantgarde_DPF7_Sitz...,privat,Angebot,"$4,999",test,kombi,2004,automatik,204,e_klasse,"150,000km",10,diesel,mercedes_benz,nein,2016-04-02 00:00:00,0,47638,2016-04-02 12:45:44
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49970,2016-03-21 22:47:37,c4_Grand_Picasso_mit_Automatik_Leder_Navi_Temp...,privat,Angebot,"$15,800",control,bus,2010,automatik,136,c4,"60,000km",4,diesel,citroen,nein,2016-03-21 00:00:00,0,14947,2016-04-07 04:17:34
49971,2016-03-29 14:54:12,W.Lupo_1.0,privat,Angebot,$950,test,kleinwagen,2001,manuell,50,lupo,"150,000km",4,benzin,volkswagen,nein,2016-03-29 00:00:00,0,65197,2016-03-29 20:41:51
49972,2016-03-26 22:25:23,Mercedes_Benz_Vito_115_CDI_Extralang_Aut.,privat,Angebot,"$3,300",control,bus,2004,automatik,150,vito,"150,000km",10,diesel,mercedes_benz,ja,2016-03-26 00:00:00,0,65326,2016-03-28 11:28:18
49973,2016-03-27 05:32:39,Mercedes_Benz_SLK_200_Kompressor,privat,Angebot,"$6,000",control,cabrio,2004,manuell,163,slk,"150,000km",11,benzin,mercedes_benz,nein,2016-03-27 00:00:00,0,53567,2016-03-27 08:25:24
49974,2016-03-20 10:52:31,Golf_1_Cabrio_Tuev_Neu_viele_Extras_alles_eing...,privat,Angebot,$0,control,cabrio,1983,manuell,70,golf,"150,000km",2,benzin,volkswagen,nein,2016-03-20 00:00:00,0,8209,2016-03-27 19:48:16
49975,2016-03-27 20:51:39,Honda_Jazz_1.3_DSi_i_VTEC_IMA_CVT_Comfort,privat,Angebot,"$9,700",control,kleinwagen,2012,automatik,88,jazz,"100,000km",11,hybrid,honda,nein,2016-03-27 00:00:00,0,84385,2016-04-05 19:45:34
49976,2016-03-19 18:56:05,Audi_80_Avant_2.6_E__Vollausstattung!!_Einziga...,privat,Angebot,"$5,900",test,kombi,1992,automatik,150,80,"150,000km",12,benzin,audi,nein,2016-03-19 00:00:00,0,36100,2016-04-07 06:16:44
49977,2016-03-31 18:37:18,Mercedes_Benz_C200_Cdi_W203,privat,Angebot,"$5,500",control,limousine,2003,manuell,116,c_klasse,"150,000km",2,diesel,mercedes_benz,nein,2016-03-31 00:00:00,0,33739,2016-04-06 12:16:11
49978,2016-04-04 10:37:14,Mercedes_Benz_E_200_Classic,privat,Angebot,$900,control,limousine,1996,automatik,136,e_klasse,"150,000km",9,benzin,mercedes_benz,ja,2016-04-04 00:00:00,0,24405,2016-04-06 12:44:20
49979,2016-03-20 18:38:40,Volkswagen_Polo_1.6_TDI_Style,privat,Angebot,"$11,000",test,kleinwagen,2011,manuell,90,polo,"70,000km",11,diesel,volkswagen,nein,2016-03-20 00:00:00,0,48455,2016-04-07 01:45:12
49980,2016-03-12 10:55:54,Ford_Escort_Turnier_16V,privat,Angebot,$400,control,kombi,1995,manuell,105,escort,"125,000km",3,benzin,ford,NaN,2016-03-12 00:00:00,0,56218,2016-04-06 17:16:49
49981,2016-03-15 09:38:21,Opel_Astra_Kombi_mit_Anhaengerkupplung,privat,Angebot,"$2,000",control,kombi,1998,manuell,115,astra,"150,000km",12,benzin,opel,nein,2016-03-15 00:00:00,0,86859,2016-04-05 17:21:46
49982,2016-03-29 18:51:08,Skoda_Fabia_4_Tuerer_Bj:2004__85.000Tkm,privat,Angebot,"$1,950",control,kleinwagen,2004,manuell,0,fabia,"90,000km",7,benzin,skoda,NaN,2016-03-29 00:00:00,0,45884,2016-03-29 18:51:08
49983,2016-03-06 12:43:04,Ford_focus_99,privat,Angebot,$600,test,kleinwagen,1999,manuell,101,focus,"150,000km",4,benzin,ford,NaN,2016-03-06 00:00:00,0,52477,2016-03-09 06:16:08
49984,2016-03-31 22:48:48,Student_sucht_ein__Anfaengerauto___ab_2000_BJ_...,privat,Angebot,$0,test,NaN,2000,NaN,0,NaN,"150,000km",0,NaN,sonstige_autos,NaN,2016-03-31 00:00:00,0,12103,2016-04-02 19:44:53
49985,2016-04-02 16:38:23,Verkaufe_meinen_vw_vento!,privat,Angebot,"$1,000",control,NaN,1995,automatik,0,NaN,"150,000km",0,benzin,volkswagen,NaN,2016-04-02 00:00:00,0,30900,2016-04-06 15:17:52
49986,2016-04-04 20:46:02,Chrysler_300C_3.0_CRD_DPF_Automatik_Voll_Ausst...,privat,Angebot,"$15,900",control,limousine,2010,automatik,218,300c,"125,000km",11,diesel,chrysler,nein,2016-04-04 00:00:00,0,73527,2016-04-06 23:16:00
49987,2016-03-22 20:47:27,Audi_A3_Limousine_2.0_TDI_DPF_Ambition__NAVI__...,privat,Angebot,"$21,990",control,limousine,2013,manuell,150,a3,"50,000km",11,diesel,audi,nein,2016-03-22 00:00:00,0,94362,2016-03-26 22:46:06
49988,2016-03-28 19:49:51,BMW_330_Ci,privat,Angebot,"$9,550",control,coupe,2001,manuell,231,3er,"150,000km",10,benzin,bmw,nein,2016-03-28 00:00:00,0,83646,2016-04-07 02:17:40
49989,2016-03-11 19:50:37,VW_Polo_zum_Ausschlachten_oder_Wiederaufbau,privat,Angebot,$150,test,kleinwagen,1997,manuell,0,polo,"150,000km",5,benzin,volkswagen,ja,2016-03-11 00:00:00,0,21244,2016-03-12 10:17:55
49990,2016-03-21 19:54:19,Mercedes_Benz_A_200__BlueEFFICIENCY__Urban,privat,Angebot,"$17,500",test,limousine,2012,manuell,156,a_klasse,"30,000km",12,benzin,mercedes_benz,nein,2016-03-21 00:00:00,0,58239,2016-04-06 22:46:57
49991,2016-03-06 15:25:19,Kleinwagen,privat,Angebot,$500,control,NaN,2016,manuell,0,twingo,"150,000km",0,benzin,renault,NaN,2016-03-06 00:00:00,0,61350,2016-03-06 18:24:19
49992,2016-03-10 19:37:38,Fiat_Grande_Punto_1.4_T_Jet_16V_Sport,privat,Angebot,"$4,800",control,kleinwagen,2009,manuell,120,andere,"125,000km",9,lpg,fiat,nein,2016-03-10 00:00:00,0,68642,2016-03-13 01:44:51
49993,2016-03-15 18:47:35,Audi_A3__1_8l__Silber;_schoenes_Fahrzeug,privat,Angebot,"$1,650",control,kleinwagen,1997,manuell,0,NaN,"150,000km",7,benzin,audi,NaN,2016-03-15 00:00:00,0,65203,2016-04-06 19:46:53
49994,2016-03-22 17:36:42,Audi_A6__S6__Avant_4.2_quattro_eventuell_Tausc...,privat,Angebot,"$5,000",control,kombi,2001,automatik,299,a6,"150,000km",1,benzin,audi,nein,2016-03-22 00:00:00,0,46537,2016-04-06 08:16:39
49995,2016-03-27 14:38:19,Audi_Q5_3.0_TDI_qu._S_tr.__Navi__Panorama__Xenon,privat,Angebot,"$24,900",control,limousine,2011,automatik,239,q5,"100,000km",1,diesel,audi,nein,2016-03-27 00:00:00,0,82131,2016-04-01 13:47:40
49996,2016-03-28 10:50:25,Opel_Astra_F_Cabrio_Bertone_Edition___TÃœV_neu+...,privat,Angebot,"$1,980",control,cabrio,1996,manuell,75,astra,"150,000km",5,benzin,opel,nein,2016-03-28 00:00:00,0,44807,2016-04-02 14:18:02
49997,2016-04-02 14:44:48,Fiat_500_C_1.2_Dualogic_Lounge,privat,Angebot,"$13,200",test,cabrio,2014,automatik,69,500,"5,000km",11,benzin,fiat,nein,2016-04-02 00:00:00,0,73430,2016-04-04 11:47:27
49998,2016-03-08 19:25:42,Audi_A3_2.0_TDI_Sportback_Ambition,privat,Angebot,"$22,900",control,kombi,2013,manuell,150,a3,"40,000km",11,diesel,audi,nein,2016-03-08 00:00:00,0,35683,2016-04-05 16:45:07
49999,2016-03-14 00:42:12,Opel_Vectra_1.6_16V,privat,Angebot,"$1,250",control,limousine,1996,manuell,101,vectra,"150,000km",1,benzin,opel,nein,2016-03-13 00:00:00,0,45897,2016-04-06 21:18:48

In [3]:
autos.columns

Index(['dateCrawled', 'name', 'seller', 'offerType', 'price', 'abtest',
       'vehicleType', 'yearOfRegistration', 'gearbox', 'powerPS', 'model',
       'odometer', 'monthOfRegistration', 'fuelType', 'brand',
       'notRepairedDamage', 'dateCreated', 'nrOfPictures', 'postalCode',
       'lastSeen'],
      dtype='object')

In [4]:
autos.columns = ['date_crawled', 'name', 'seller', 'offer_type', 'price', 'abtest',
       'vehicle_type', 'registration_year', 'gearbox', 'powerPS', 'model',
       'odometer_km', 'registration_month', 'fuel_type', 'brand',
       'unrepaired_damage', 'ad_created', 'nr_of_pictures', 'postal_code',
       'last_seen']

In [5]:
autos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 20 columns):
date_crawled          50000 non-null object
name                  50000 non-null object
seller                50000 non-null object
offer_type            50000 non-null object
price                 50000 non-null object
abtest                50000 non-null object
vehicle_type          44905 non-null object
registration_year     50000 non-null int64
gearbox               47320 non-null object
powerPS               50000 non-null int64
model                 47242 non-null object
odometer_km           50000 non-null object
registration_month    50000 non-null int64
fuel_type             45518 non-null object
brand                 50000 non-null object
unrepaired_damage     40171 non-null object
ad_created            50000 non-null object
nr_of_pictures        50000 non-null int64
postal_code           50000 non-null int64
last_seen             50000 non-null object
dtypes: int64(5), object(15)
memory usage: 7.6+ MB

The dataset contains 20 columns, most of which are 'non-null objects' (= strings). 

We can see that the column values in 'price' are strings. Upon closer inspection, we can see that the values contain the '$' symbol.

The 'odometer' column has text values, which need to be converted into numerical values.

We can see that there are almost 9000 cases of missing data on notRepairedDamage (showing if the car has damage which is not yet repaired).

Also, fuelType data is missing in around 4500 cases.

In [6]:
autos.head()

,date_crawled,name,seller,offer_type,price,abtest,vehicle_type,registration_year,gearbox,powerPS,model,odometer_km,registration_month,fuel_type,brand,unrepaired_damage,ad_created,nr_of_pictures,postal_code,last_seen
0,2016-03-26 17:47:46,Peugeot_807_160_NAVTECH_ON_BOARD,privat,Angebot,"$5,000",control,bus,2004,manuell,158,andere,"150,000km",3,lpg,peugeot,nein,2016-03-26 00:00:00,0,79588,2016-04-06 06:45:54
1,2016-04-04 13:38:56,BMW_740i_4_4_Liter_HAMANN_UMBAU_Mega_Optik,privat,Angebot,"$8,500",control,limousine,1997,automatik,286,7er,"150,000km",6,benzin,bmw,nein,2016-04-04 00:00:00,0,71034,2016-04-06 14:45:08
2,2016-03-26 18:57:24,Volkswagen_Golf_1.6_United,privat,Angebot,"$8,990",test,limousine,2009,manuell,102,golf,"70,000km",7,benzin,volkswagen,nein,2016-03-26 00:00:00,0,35394,2016-04-06 20:15:37
3,2016-03-12 16:58:10,Smart_smart_fortwo_coupe_softouch/F1/Klima/Pan...,privat,Angebot,"$4,350",control,kleinwagen,2007,automatik,71,fortwo,"70,000km",6,benzin,smart,nein,2016-03-12 00:00:00,0,33729,2016-03-15 03:16:28
4,2016-04-01 14:38:50,Ford_Focus_1_6_Benzin_TÃœV_neu_ist_sehr_gepfleg...,privat,Angebot,"$1,350",test,kombi,2003,manuell,0,focus,"150,000km",7,benzin,ford,nein,2016-04-01 00:00:00,0,39218,2016-04-01 14:38:50

When examining the columns and values, I suspect the model column being an open text field on Ebay. Below, I will count the number of different models.

In [7]:
autos['model'].value_counts()

golf                  4024
andere                3528
3er                   2761
polo                  1757
corsa                 1735
astra                 1454
passat                1425
a4                    1291
5er                   1183
c_klasse              1172
e_klasse              1001
a3                     882
a6                     835
focus                  811
fiesta                 769
transporter            704
twingo                 677
2_reihe                621
a_klasse               588
vectra                 574
fortwo                 574
1er                    538
clio                   509
3_reihe                508
mondeo                 496
touran                 468
punto                  458
zafira                 423
ka                     370
megane                 362
                      ...
gl                      12
lanos                   12
range_rover_sport       12
move                    10
r19                     10
lybra                   10
mii                     10
terios                  10
range_rover              9
90                       9
nubira                   8
exeo                     7
amarok                   7
crossfire                6
9000                     6
delta                    6
145                      5
lodgy                    5
croma                    5
range_rover_evoque       5
samara                   4
materia                  4
v60                      3
charade                  3
kappa                    2
kalina                   2
200                      1
i3                       1
rangerover               1
b_max                    1
Name: model, Length: 245, dtype: int64

We can see that there are 245 different models. Some model names are suspected of being the same but expressed differently (f.e. in German instead of English: 2_reihe == 2_series). We will need to transform these modelnames later on.

Next, we can see that the model 'andere' (which translates to 'other') is very popular. It is unclear what models are in the 'other' category.

In [8]:
autos['registration_year'].value_counts()

2000    3354
2005    3015
1999    3000
2004    2737
2003    2727
2006    2708
2001    2703
2002    2533
1998    2453
2007    2304
2008    2231
2009    2098
1997    2028
2011    1634
2010    1597
2017    1453
1996    1444
2012    1323
2016    1316
1995    1313
2013     806
2014     666
1994     660
2018     492
1993     445
2015     399
1990     395
1992     391
1991     356
1989     181
        ...
1950       3
1955       2
9000       2
1954       2
1800       2
1957       2
1941       2
1951       2
1934       2
4100       1
4800       1
1953       1
1111       1
1927       1
6200       1
4500       1
1943       1
5911       1
1939       1
1938       1
2800       1
8888       1
1000       1
1500       1
1948       1
1931       1
1929       1
1001       1
9996       1
1952       1
Name: registration_year, Length: 97, dtype: int64

Examining the yearOfRegistration column reveals that it contains registration dates which are unrealistic (f.e. 8888, 1000, 1500).

In [9]:
autos['price'].value_counts().head()

$0        1421
$500       781
$1,500     734
$2,500     643
$1,000     639
Name: price, dtype: int64

As we can see, we need to remove the dollar signs and turn the values into numerical values so we can analyse prices further.

We can see that there are many cars without price in the list, scewing the distribution. It is possible that these cars are listed without price so that people can bid on them

It would be interesting to split cars with and without price.

In [10]:
autos.describe()

,registration_year,powerPS,registration_month,nr_of_pictures,postal_code
count,50000.000000,50000.000000,50000.000000,50000.0,50000.000000
mean,2005.073280,116.355920,5.723360,0.0,50813.627300
std,105.712813,209.216627,3.711984,0.0,25779.747957
min,1000.000000,0.000000,0.000000,0.0,1067.000000
25%,1999.000000,70.000000,3.000000,0.0,30451.000000
50%,2003.000000,105.000000,6.000000,0.0,49577.000000
75%,2008.000000,150.000000,9.000000,0.0,71540.000000
max,9999.000000,17700.000000,12.000000,0.0,99998.000000

Going through the columns, we can easily spot some unrealistic values:

Year of Registration contains a max value of 9999 and a min of 1000.

powerPS (metric horsepower) has a min value of 0 and a max value 17700.

Also, every car in the dataset has 0 number of pictures.

Month of registration min is 0. This should probably be a null-value instead.

In [11]:
autos.describe(include='all')

,date_crawled,name,seller,offer_type,price,abtest,vehicle_type,registration_year,gearbox,powerPS,model,odometer_km,registration_month,fuel_type,brand,unrepaired_damage,ad_created,nr_of_pictures,postal_code,last_seen
count,50000,50000,50000,50000,50000,50000,44905,50000.000000,47320,50000.000000,47242,50000,50000.000000,45518,50000,40171,50000,50000.0,50000.000000,50000
unique,48213,38754,2,2,2357,2,8,NaN,2,NaN,245,13,NaN,7,40,2,76,NaN,NaN,39481
top,2016-03-21 20:37:19,Ford_Fiesta,privat,Angebot,$0,test,limousine,NaN,manuell,NaN,golf,"150,000km",NaN,benzin,volkswagen,nein,2016-04-03 00:00:00,NaN,NaN,2016-04-07 06:17:27
freq,3,78,49999,49999,1421,25756,12859,NaN,36993,NaN,4024,32424,NaN,30107,10687,35232,1946,NaN,NaN,8
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2005.073280,NaN,116.355920,NaN,NaN,5.723360,NaN,NaN,NaN,NaN,0.0,50813.627300,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,105.712813,NaN,209.216627,NaN,NaN,3.711984,NaN,NaN,NaN,NaN,0.0,25779.747957,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1000.000000,NaN,0.000000,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,0.0,1067.000000,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1999.000000,NaN,70.000000,NaN,NaN,3.000000,NaN,NaN,NaN,NaN,0.0,30451.000000,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2003.000000,NaN,105.000000,NaN,NaN,6.000000,NaN,NaN,NaN,NaN,0.0,49577.000000,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2008.000000,NaN,150.000000,NaN,NaN,9.000000,NaN,NaN,NaN,NaN,0.0,71540.000000,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9999.000000,NaN,17700.000000,NaN,NaN,12.000000,NaN,NaN,NaN,NaN,0.0,99998.000000,NaN

### Cleaning

From the table above, we can note that some columns contain mostly one value (and are thus not adding anything to our analysis):

- seller: This column contains only 1 'commercial' value, the rest is 'privat'.
- offer_type
- nr of pictures: This column contains only '0.0' values.

We will drop these columns.

Another thing striking is the top vehicle type: Limousine.
- Investigate vehicle types.

As seen earlier, we will perform the following cleaning actions:

- Remove $ from 'price' and turn it into integer.
- Turn 'odometer' into integer.
- Split price between '0' and '>0'
- Remove unrealistic prices, registration years, powerPS, odometer, registration month.
- Investigate 'unrepaired damage' null-values.
- Investigate 'name' and 'model'.

In [12]:
## dropping columns
autos = autos.drop(columns = ['seller', 'offer_type', 'nr_of_pictures'])

## removing any non-numeric character from price and odometer
autos['price'].replace(regex=True,inplace=True,to_replace=r'\D',value=r'')
autos['odometer_km'].replace(regex=True,inplace=True,to_replace=r'\D',value=r'')

## changing datatype into integer
autos['price'] = autos['price'].astype('int64');
autos['odometer_km'] = autos['odometer_km'].astype('int64');

In [13]:
autos['price'].head(3)

0    5000
1    8500
2    8990
Name: price, dtype: int64

In [14]:
autos['odometer_km'].head(3)

0    150000
1    150000
2     70000
Name: odometer_km, dtype: int64

In [15]:
## determining threshold for price
autos['price'].sort_values().tail(10)

7814      1300000
47634     3890000
11137    10000000
24384    11111111
2897     11111111
27371    12345678
47598    12345678
39377    12345678
42221    27322222
39705    99999999
Name: price, dtype: int64

We can see that the prices are becoming unrealistic from 10 million and upwards.

In [16]:
autos.sort_values(by='price')

,date_crawled,name,price,abtest,vehicle_type,registration_year,gearbox,powerPS,model,odometer_km,registration_month,fuel_type,brand,unrepaired_damage,ad_created,postal_code,last_seen
18089,2016-03-16 15:51:44,VW_Polo_preiswert_zu_verkaufen,0,test,NaN,2016,manuell,0,polo,150000,5,benzin,volkswagen,NaN,2016-03-16 00:00:00,15345,2016-03-16 15:51:44
43923,2016-03-25 00:56:44,Focus_Diesel_zum_ausschlachten,0,control,NaN,2016,NaN,90,focus,150000,1,diesel,ford,ja,2016-03-24 00:00:00,74251,2016-03-29 20:16:48
15225,2016-03-12 10:55:13,Audi_a3_1_8T,0,control,NaN,2016,automatik,190,a3,150000,11,benzin,audi,nein,2016-03-12 00:00:00,9471,2016-04-06 02:46:45
29499,2016-03-24 21:56:38,_TUNING_GRUNE_PLAKETTE_EURO_4_,0,test,bus,2005,manuell,101,vivaro,80000,8,diesel,opel,nein,2016-03-24 00:00:00,44869,2016-03-24 21:56:38
8445,2016-03-25 20:53:17,Suche_Audi_a6_4,0,control,kombi,2005,NaN,0,a6,150000,0,NaN,audi,NaN,2016-03-25 00:00:00,39112,2016-04-01 06:44:51
38832,2016-03-10 15:47:28,Opel_Corsa_B_mit_Schiebedach_Alufelgen_&_TÃœV_b...,0,test,kleinwagen,1996,manuell,50,corsa,150000,11,benzin,opel,nein,2016-03-10 00:00:00,23552,2016-03-16 02:16:59
43925,2016-03-15 12:51:38,Golf_3_gti_Jubilaeum_Edition,0,control,kleinwagen,1996,manuell,115,golf,70000,7,benzin,volkswagen,NaN,2016-03-15 00:00:00,23923,2016-03-22 12:45:36
8438,2016-03-14 21:37:21,Jaguar_xj_40_Daimler_Original_Baujahr_1994,0,test,NaN,1995,automatik,0,NaN,5000,3,NaN,jaguar,nein,2016-03-14 00:00:00,12099,2016-03-25 11:45:38
35821,2016-04-01 18:48:07,Tausche_gegen_Gold_/_Silber_oder_gleichwertige...,0,control,bus,1970,NaN,0,transporter,5000,5,NaN,volkswagen,NaN,2016-04-01 00:00:00,97070,2016-04-01 18:48:07
31332,2016-03-07 15:56:14,Renault_clio_1.2_16_v_RT,0,control,limousine,2001,manuell,75,clio,90000,6,NaN,renault,NaN,2016-03-07 00:00:00,51107,2016-03-10 15:45:53
12819,2016-03-08 21:49:42,VW_Bora__Tausch_,0,control,NaN,2005,NaN,0,bora,150000,0,benzin,volkswagen,NaN,2016-03-08 00:00:00,94447,2016-03-29 18:44:44
33620,2016-03-26 18:39:00,VW_Jetta_Oldtimer_Youngtimer_Sammler_Retro_1.8...,0,test,NaN,2018,automatik,90,NaN,150000,3,NaN,volkswagen,nein,2016-03-26 00:00:00,73463,2016-04-06 07:44:48
15208,2016-03-19 09:39:15,BMW_E39_520_Tempomat_Xenon_TÃœV_4/17_188.000km,0,test,limousine,1996,manuell,150,5er,150000,6,benzin,bmw,nein,2016-03-19 00:00:00,57072,2016-03-31 14:46:21
2481,2016-04-04 11:47:53,Triton_Supermoto_400_ccm_Tuev_9/17_!_Verkauf_/...,0,control,NaN,2017,automatik,0,NaN,10000,2,benzin,sonstige_autos,NaN,2016-04-04 00:00:00,58708,2016-04-06 12:46:49
4266,2016-03-08 17:53:09,Passat_3b_kombi,0,control,NaN,2017,automatik,125,passat,150000,0,NaN,volkswagen,nein,2016-03-08 00:00:00,25566,2016-03-10 13:45:25
27020,2016-03-31 16:38:27,wollen_Sie_Ihr_Auto_Verkaufen___wir_Kaufen_KFZ_an,0,control,NaN,2007,NaN,0,andere,150000,7,NaN,mazda,ja,2016-03-31 00:00:00,13467,2016-03-31 16:38:27
35819,2016-03-24 10:56:50,Alfa_Romeo_Spider,0,test,NaN,2005,NaN,0,spider,150000,0,NaN,alfa_romeo,NaN,2016-03-24 00:00:00,73431,2016-04-07 01:47:00
31336,2016-03-21 08:36:17,Peugeot_206_1_4_75_PS_TOP_im_Tausch_gegen_Komb...,0,control,limousine,2002,manuell,75,2_reihe,150000,2,benzin,peugeot,nein,2016-03-21 00:00:00,53506,2016-04-05 22:45:19
29482,2016-04-03 20:58:55,Daihatsu_Cuore,0,test,kleinwagen,2002,manuell,56,cuore,150000,9,benzin,daihatsu,NaN,2016-04-03 00:00:00,85221,2016-04-03 20:58:55
47861,2016-03-29 11:54:52,W211_Stossdaempfer_vorne,0,test,limousine,2003,NaN,0,e_klasse,150000,10,NaN,mercedes_benz,NaN,2016-03-29 00:00:00,49205,2016-04-05 21:45:36
21253,2016-03-12 15:49:05,Audi_80_B4_Limousine,0,control,limousine,1994,manuell,90,80,150000,0,benzin,audi,NaN,2016-03-12 00:00:00,36396,2016-04-07 04:17:09
37021,2016-03-08 17:39:51,Suche_SLK__R_170_Automatik,0,control,cabrio,1998,automatik,0,slk,150000,0,benzin,mercedes_benz,NaN,2016-03-08 00:00:00,56743,2016-03-11 00:15:08
29503,2016-03-09 10:47:37,Golf_3___Baujahr_96__1_6_l,0,control,NaN,2000,NaN,0,golf,150000,0,NaN,volkswagen,NaN,2016-03-09 00:00:00,16866,2016-03-15 07:16:13
21256,2016-03-20 11:36:56,VW_GOLF_2_TÃœV_BBS_Tausch_moeglich,0,test,NaN,2017,manuell,70,golf,150000,3,benzin,volkswagen,NaN,2016-03-20 00:00:00,12524,2016-03-20 11:36:56
2470,2016-03-05 15:49:58,Opel_Astra_Coupe,0,control,coupe,2004,manuell,125,astra,125000,4,benzin,opel,nein,2016-03-05 00:00:00,37339,2016-03-06 04:45:26
24871,2016-03-29 09:37:36,Golf_6_GTD_DSG_*Standheizung*_*Tausch_moeglich*,0,test,NaN,2016,automatik,180,golf,150000,7,diesel,volkswagen,NaN,2016-03-29 00:00:00,38124,2016-03-31 02:45:26
31264,2016-04-02 22:38:54,opel_astra_g,0,test,NaN,2016,manuell,103,astra,150000,0,benzin,opel,NaN,2016-04-02 00:00:00,92526,2016-04-04 22:15:44
1220,2016-03-30 13:55:32,Opel_Corsa_C_1__2_Liter_mit_Klima_TÃœV_bis_10.2017,0,test,NaN,2005,NaN,75,corsa,150000,5,NaN,opel,NaN,2016-03-30 00:00:00,49477,2016-03-30 14:42:13
24900,2016-03-16 14:37:54,VW_Golf_4___Diesel,0,test,NaN,2017,NaN,0,golf,150000,0,diesel,volkswagen,NaN,2016-03-16 00:00:00,29614,2016-04-06 12:45:45
21171,2016-03-11 19:50:48,Opel_vectra_b_super_Zustand,0,test,limousine,1998,automatik,170,vectra,150000,5,benzin,opel,nein,2016-03-11 00:00:00,32369,2016-03-13 01:16:48
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18509,2016-03-27 18:43:02,Porsche_991_GT3,169000,control,coupe,2013,automatik,476,911,20000,9,benzin,porsche,nein,2016-03-27 00:00:00,83629,2016-04-05 15:15:29
32840,2016-03-22 08:55:27,Mercedes_Benz_G_500_7G_TRONIC_Cabrio_Desingno_...,169999,control,cabrio,2012,automatik,387,g_klasse,40000,3,benzin,mercedes_benz,nein,2016-03-22 00:00:00,42655,2016-04-05 20:47:17
11433,2016-03-30 21:44:21,Audi_R8_V10_plus_5.2_FSI_quattro_S_tronic_Akra...,175000,test,coupe,2016,automatik,610,andere,5000,1,benzin,audi,nein,2016-03-30 00:00:00,94244,2016-04-05 11:46:33
17140,2016-03-05 17:39:22,Mercedes_Benz_SLS_AMG_Roadster_AMG_SPEEDSHIFT_DCT,180000,test,cabrio,2012,automatik,571,andere,50000,2,benzin,mercedes_benz,nein,2016-03-05 00:00:00,14193,2016-03-20 19:44:36
20351,2016-03-22 17:47:59,BMW_Z8_roadster,190000,control,cabrio,2000,manuell,400,z_reihe,60000,9,benzin,bmw,nein,2016-03-22 00:00:00,14473,2016-04-02 11:44:28
28090,2016-03-08 19:50:06,Tesla_Model_X_P90D_Signature_Sondermodel__Neuw...,194000,test,suv,2016,automatik,0,NaN,5000,3,elektro,sonstige_autos,nein,2016-03-08 00:00:00,97990,2016-03-16 04:15:31
43668,2016-03-16 18:47:26,Porsche_993/911_Turbo_WLS_II_Exclusive_S_deuts...,197000,control,coupe,1998,manuell,450,911,150000,3,NaN,porsche,nein,2016-03-16 00:00:00,46147,2016-04-07 02:44:47
40918,2016-03-20 18:40:05,Porsche_911_991_GT3_RS,198000,test,coupe,2015,automatik,500,911,5000,6,benzin,porsche,nein,2016-03-20 00:00:00,51491,2016-03-21 21:46:36
37840,2016-03-21 10:50:12,Porsche_997,220000,test,coupe,2008,manuell,415,911,30000,7,benzin,porsche,nein,2016-03-21 00:00:00,69198,2016-04-06 04:46:14
38299,2016-03-28 22:25:25,Glas_BMW_mit_Wasser,250000,test,NaN,2015,NaN,0,x_reihe,5000,0,NaN,bmw,NaN,2016-03-28 00:00:00,60489,2016-03-28 22:25:25
47337,2016-04-05 10:25:38,BMW_Z8_roadster,259000,test,cabrio,2001,manuell,400,z_reihe,20000,6,benzin,bmw,nein,2016-04-05 00:00:00,61462,2016-04-05 12:07:32
12682,2016-03-28 22:48:01,Porsche_GT3_RS__PCCB__Lift___grosser_Exklusiv_...,265000,control,coupe,2016,automatik,500,911,5000,3,benzin,porsche,nein,2016-03-28 00:00:00,70193,2016-04-05 03:44:51
35923,2016-04-03 07:56:23,Porsche_911_Targa_Exclusive_Edition__1_von_15_...,295000,test,cabrio,2015,automatik,400,911,5000,6,benzin,porsche,nein,2016-04-03 00:00:00,74078,2016-04-03 08:56:20
34723,2016-03-23 16:37:29,Porsche_Porsche_911/930_Turbo_3.0__deutsche_Au...,299000,test,coupe,1977,manuell,260,911,100000,7,benzin,porsche,nein,2016-03-23 00:00:00,61462,2016-04-06 16:44:50
14715,2016-03-30 08:37:24,Rolls_Royce_Phantom_Drophead_Coupe,345000,control,cabrio,2012,automatik,460,NaN,20000,8,benzin,sonstige_autos,nein,2016-03-30 00:00:00,73525,2016-04-07 00:16:26
36818,2016-03-27 18:37:37,Porsche_991,350000,control,coupe,2016,manuell,500,911,5000,3,benzin,porsche,nein,2016-03-27 00:00:00,70499,2016-03-27 18:37:37
37585,2016-03-29 11:38:54,Volkswagen_Jetta_GT,999990,test,limousine,1985,manuell,111,jetta,150000,12,benzin,volkswagen,ja,2016-03-29 00:00:00,50997,2016-03-29 11:38:54
514,2016-03-17 09:53:08,Ford_Focus_Turnier_1.6_16V_Style,999999,test,kombi,2009,manuell,101,focus,125000,4,benzin,ford,nein,2016-03-17 00:00:00,12205,2016-04-06 07:17:35
43049,2016-03-21 19:53:52,2_VW_Busse_T3,999999,test,bus,1981,manuell,70,transporter,150000,1,benzin,volkswagen,NaN,2016-03-21 00:00:00,99880,2016-03-28 17:18:28
22947,2016-03-22 12:54:19,Bmw_530d_zum_ausschlachten,1234566,control,kombi,1999,automatik,190,NaN,150000,2,diesel,bmw,NaN,2016-03-22 00:00:00,17454,2016-04-02 03:17:32
7814,2016-04-04 11:53:31,Ferrari_F40,1300000,control,coupe,1992,NaN,0,NaN,50000,12,NaN,sonstige_autos,nein,2016-04-04 00:00:00,60598,2016-04-05 11:34:11
47634,2016-04-04 21:25:21,Ferrari_FXX,3890000,test,coupe,2006,NaN,799,NaN,5000,7,NaN,sonstige_autos,nein,2016-04-04 00:00:00,60313,2016-04-05 12:07:37
11137,2016-03-29 23:52:57,suche_maserati_3200_gt_Zustand_unwichtig_laufe...,10000000,control,coupe,1960,manuell,368,NaN,100000,1,benzin,sonstige_autos,nein,2016-03-29 00:00:00,73033,2016-04-06 21:18:11
24384,2016-03-21 13:57:51,Schlachte_Golf_3_gt_tdi,11111111,test,NaN,1995,NaN,0,NaN,150000,0,NaN,volkswagen,NaN,2016-03-21 00:00:00,18519,2016-03-21 14:40:18
2897,2016-03-12 21:50:57,Escort_MK_1_Hundeknochen_zum_umbauen_auf_RS_2000,11111111,test,limousine,1973,manuell,48,escort,50000,3,benzin,ford,nein,2016-03-12 00:00:00,94469,2016-03-12 22:45:27
27371,2016-03-09 15:45:47,Fiat_Punto,12345678,control,NaN,2017,NaN,95,punto,150000,0,NaN,fiat,NaN,2016-03-09 00:00:00,96110,2016-03-09 15:45:47
47598,2016-03-31 18:56:54,Opel_Vectra_B_1_6i_16V_Facelift_Tuning_Showcar...,12345678,control,limousine,2001,manuell,101,vectra,150000,3,benzin,opel,nein,2016-03-31 00:00:00,4356,2016-03-31 18:56:54
39377,2016-03-08 23:53:51,Tausche_volvo_v40_gegen_van,12345678,control,NaN,2018,manuell,95,v40,150000,6,NaN,volvo,nein,2016-03-08 00:00:00,14542,2016-04-06 23:17:31
42221,2016-03-08 20:39:05,Leasinguebernahme,27322222,control,limousine,2014,manuell,163,c4,40000,2,diesel,citroen,NaN,2016-03-08 00:00:00,76532,2016-03-08 20:39:05
39705,2016-03-22 14:58:27,Tausch_gegen_gleichwertiges,99999999,control,limousine,1999,automatik,224,s_klasse,150000,9,benzin,mercedes_benz,NaN,2016-03-22 00:00:00,73525,2016-04-06 05:15:30

When examining the most expensive cars, we can see that it doesn't make sense. Exclusive ferrari's second hand on Ebay along with expensive Volkswagen busses. We remove these values.

In [17]:
## removing outliers price
autos = autos[(autos["price"] <= 350000)]

Another striking thing is the high number (1421) of cars with price '0'. Let's examine this category further:

In [18]:
autos[autos.price == 0]

,date_crawled,name,price,abtest,vehicle_type,registration_year,gearbox,powerPS,model,odometer_km,registration_month,fuel_type,brand,unrepaired_damage,ad_created,postal_code,last_seen
27,2016-03-27 18:45:01,Hat_einer_Ahnung_mit_Ford_Galaxy_HILFE,0,control,NaN,2005,NaN,0,NaN,150000,0,NaN,ford,NaN,2016-03-27 00:00:00,66701,2016-03-27 18:45:01
71,2016-03-28 19:39:35,Suche_Opel_Astra_F__Corsa_oder_Kadett_E_mit_Re...,0,control,NaN,1990,manuell,0,NaN,5000,0,benzin,opel,NaN,2016-03-28 00:00:00,4552,2016-04-07 01:45:48
80,2016-03-09 15:57:57,Nissan_Primera_Hatchback_1_6_16v_73_Kw___99Ps_...,0,control,coupe,1999,manuell,99,primera,150000,3,benzin,nissan,ja,2016-03-09 00:00:00,66903,2016-03-09 16:43:50
87,2016-03-29 23:37:22,Bmw_520_e39_zum_ausschlachten,0,control,NaN,2000,NaN,0,5er,150000,0,NaN,bmw,NaN,2016-03-29 00:00:00,82256,2016-04-06 21:18:15
99,2016-04-05 09:48:54,Peugeot_207_CC___Cabrio_Bj_2011,0,control,cabrio,2011,manuell,0,2_reihe,60000,7,diesel,peugeot,nein,2016-04-05 00:00:00,99735,2016-04-07 12:17:34
118,2016-03-12 05:03:00,VW_Sharan_V6_204_PS_Karosse_Rohkarosse_mit_Pap...,0,control,bus,2001,manuell,204,sharan,150000,7,benzin,volkswagen,ja,2016-03-12 00:00:00,15370,2016-03-12 21:44:23
146,2016-03-22 23:59:28,Ford_Fiesta_rot,0,test,kleinwagen,1996,manuell,75,fiesta,20000,8,benzin,ford,NaN,2016-03-22 00:00:00,63069,2016-04-01 20:16:38
167,2016-04-02 19:43:45,Suche_VW_Multivan_Innenausstattung_Set_oder_TE...,0,control,NaN,2011,NaN,0,transporter,5000,0,NaN,volkswagen,NaN,2016-04-02 00:00:00,64739,2016-04-06 19:45:08
180,2016-03-19 10:50:25,Zu_verkaufen,0,test,NaN,2016,manuell,98,3_reihe,150000,12,benzin,mazda,ja,2016-03-19 00:00:00,30966,2016-03-24 03:17:21
226,2016-03-25 23:52:12,Porsche_911_S_Targa__67er_SWB,0,control,cabrio,1967,manuell,160,911,5000,12,benzin,porsche,nein,2016-03-25 00:00:00,44575,2016-04-05 14:46:39
234,2016-03-05 16:56:22,Fiat_Punto_Sport,0,control,NaN,2016,NaN,0,punto,150000,0,NaN,fiat,NaN,2016-03-05 00:00:00,44789,2016-03-17 22:47:09
248,2016-03-08 22:57:53,VW_Passat_zu_verkaufen,0,test,kombi,1998,manuell,0,passat,150000,10,benzin,volkswagen,ja,2016-03-08 00:00:00,34369,2016-03-29 16:16:18
259,2016-04-03 23:49:58,guenstiges_Auto_/_auch_defekt,0,control,NaN,2000,NaN,0,NaN,5000,6,NaN,sonstige_autos,NaN,2016-04-03 00:00:00,89269,2016-04-06 07:16:22
301,2016-03-08 20:37:59,Kaufe_alle_Autos_bietet_an,0,control,NaN,1990,NaN,0,NaN,5000,0,NaN,sonstige_autos,NaN,2016-03-08 00:00:00,13589,2016-04-05 18:44:43
323,2016-03-15 16:54:59,W220_Unfallfahrzeug,0,control,limousine,2001,automatik,224,s_klasse,150000,8,NaN,mercedes_benz,NaN,2016-03-15 00:00:00,45475,2016-04-06 12:44:20
327,2016-04-03 13:49:21,BMW_Cabrio_318i_/_BMW_318_tds_Touring,0,control,NaN,2016,manuell,90,3er,150000,2,diesel,bmw,NaN,2016-04-03 00:00:00,39112,2016-04-05 12:46:23
347,2016-04-02 11:48:02,Volvo_TP21__Sugga,0,test,suv,1956,NaN,0,andere,100000,0,NaN,volvo,NaN,2016-04-02 00:00:00,34414,2016-04-04 09:15:24
366,2016-03-21 20:36:25,Ford_Escort_Express_75__LKW_Zulussung___Diesel...,0,control,NaN,2000,NaN,0,andere,90000,0,diesel,ford,NaN,2016-03-21 00:00:00,3130,2016-03-28 19:16:45
389,2016-03-08 11:38:52,Vw_polo_classic,0,control,limousine,1999,manuell,75,NaN,150000,0,NaN,volkswagen,NaN,2016-03-08 00:00:00,14476,2016-03-14 09:16:30
418,2016-03-29 14:43:24,Fiat_SCUDO_8_Sitzer_Bus__Diesel_JTD__80_KW,0,test,bus,2003,manuell,80,andere,5000,5,diesel,fiat,nein,2016-03-29 00:00:00,35315,2016-04-05 23:47:14
427,2016-03-12 11:44:47,TOP_ZUSTAND_GrunePlakette_Euro4!!!,0,test,bus,2005,manuell,101,vivaro,80000,8,diesel,opel,nein,2016-03-12 00:00:00,93173,2016-03-12 11:44:47
430,2016-03-18 23:52:40,Winterraeder_FORD,0,test,NaN,2007,NaN,0,focus,5000,0,NaN,ford,NaN,2016-03-18 00:00:00,40549,2016-03-19 06:47:06
449,2016-04-03 20:59:59,Tausche_gegen_ein_smart.,0,test,limousine,2001,manuell,120,golf,150000,8,benzin,volkswagen,nein,2016-04-03 00:00:00,60439,2016-04-04 10:31:06
487,2016-03-14 21:41:36,MAG_MICH_KEINER_HABEN_Opel_Omega_B_Caravan_2.0...,0,test,kombi,1998,manuell,136,omega,150000,8,benzin,opel,ja,2016-03-14 00:00:00,59320,2016-03-17 11:48:08
502,2016-03-25 23:55:24,C32_AMG_C55_C43_w203,0,control,kombi,2001,NaN,354,c_klasse,150000,0,benzin,mercedes_benz,NaN,2016-03-25 00:00:00,79112,2016-03-26 08:40:35
519,2016-03-28 08:53:58,Verkaufe/Tausche_Seat_Inca__VW_Caddy__aus_2002...,0,test,andere,2002,manuell,64,andere,150000,2,diesel,seat,nein,2016-03-28 00:00:00,12627,2016-03-28 10:41:01
565,2016-03-20 20:49:36,Tausche_Audi_S3_8p_gegen_Golf_VI_Gti_mit_xenon,0,test,NaN,2016,manuell,330,NaN,150000,9,NaN,audi,nein,2016-03-20 00:00:00,97488,2016-03-22 00:44:53
593,2016-04-01 21:44:15,CLK_200__BRABUS_Optik,0,test,coupe,1998,manuell,136,clk,150000,1,benzin,mercedes_benz,NaN,2016-04-01 00:00:00,49191,2016-04-05 19:16:21
660,2016-03-29 21:44:40,Opel_Corsa_B,0,test,kleinwagen,1998,manuell,54,corsa,125000,11,benzin,opel,ja,2016-03-29 00:00:00,24214,2016-04-06 07:46:43
661,2016-03-18 22:49:48,Renault_Megane_Scenic_1.6_Tuev_12/17,0,test,bus,1999,manuell,0,megane,150000,8,benzin,renault,NaN,2016-03-18 00:00:00,66346,2016-03-29 16:47:09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48882,2016-03-14 23:58:47,SUCHE_AUTO,0,control,NaN,2000,NaN,0,NaN,150000,0,NaN,sonstige_autos,NaN,2016-03-14 00:00:00,97753,2016-03-30 23:47:43
48889,2016-04-01 10:50:52,Audi_A4_____TueV_09.2016,0,control,limousine,1995,manuell,101,a4,150000,2,benzin,audi,nein,2016-04-01 00:00:00,86869,2016-04-07 07:46:02
48891,2016-03-20 22:50:14,MB_E_220_CDI__TAUSCHEN_nur_SUV/GELÃ„NDEWAGEN,0,test,kombi,2001,automatik,143,e_klasse,150000,12,diesel,mercedes_benz,ja,2016-03-20 00:00:00,38442,2016-03-24 18:16:00
48982,2016-03-08 12:48:33,Bmw_525D_Sport_Pro..Navi,0,test,limousine,2010,automatik,204,5er,150000,10,diesel,bmw,NaN,2016-03-08 00:00:00,47805,2016-03-11 16:15:39
48985,2016-03-27 08:55:25,Stockcar_Autos_Peugeot,0,test,NaN,2007,NaN,60,NaN,5000,0,NaN,peugeot,NaN,2016-03-27 00:00:00,17153,2016-04-07 05:17:18
49043,2016-03-07 11:48:55,Opel_Vectra_B_Caravan,0,test,kombi,1997,manuell,101,NaN,150000,0,benzin,opel,NaN,2016-03-07 00:00:00,48429,2016-03-17 21:20:07
49082,2016-03-13 17:06:58,Passat_35i_b4_in_candy_weiss_original_lack,0,test,limousine,1996,manuell,90,NaN,150000,6,NaN,volkswagen,nein,2016-03-13 00:00:00,35799,2016-04-04 06:45:30
49254,2016-03-21 10:49:57,Corrado_G60_mit_2e_Motor,0,test,NaN,1995,manuell,0,NaN,150000,0,benzin,volkswagen,NaN,2016-03-21 00:00:00,53639,2016-03-22 15:18:35
49301,2016-03-20 20:52:40,Golf_3_Variant_Kombi_1.8,0,test,NaN,2000,NaN,0,NaN,150000,0,NaN,volkswagen,NaN,2016-03-20 00:00:00,4924,2016-03-30 15:17:15
49342,2016-03-09 20:47:01,Audi_80_b4_S_Color_und_BMW_318ti_compact_Tausc...,0,test,NaN,2017,manuell,90,80,150000,10,benzin,audi,ja,2016-03-09 00:00:00,25853,2016-03-11 17:45:36
49350,2016-03-19 23:57:15,Golf_II_Diesel,0,control,kleinwagen,1991,manuell,54,golf,150000,3,diesel,volkswagen,nein,2016-03-19 00:00:00,29664,2016-04-06 03:15:23
49404,2016-04-04 03:03:16,Golf_2_BBS_LEDER_KW,0,control,limousine,1989,manuell,90,NaN,150000,3,NaN,volkswagen,nein,2016-04-04 00:00:00,52062,2016-04-06 08:45:25
49408,2016-03-30 20:57:06,OPEL_ASTRA,0,control,NaN,1995,manuell,60,astra,150000,0,benzin,opel,ja,2016-03-30 00:00:00,27711,2016-04-05 11:46:06
49479,2016-04-01 23:55:01,Tausch_mit_frischen_TÃœV,0,control,limousine,1995,manuell,101,a4,150000,5,benzin,audi,nein,2016-04-01 00:00:00,27753,2016-04-06 05:16:07
49496,2016-03-26 13:55:28,Bmw_e39_520,0,control,limousine,1998,manuell,0,NaN,5000,0,NaN,bmw,NaN,2016-03-26 00:00:00,26188,2016-03-26 13:55:28
49504,2016-03-13 19:42:57,Meriva_Lpg_1_6_16v,0,control,bus,2004,manuell,101,meriva,150000,10,lpg,opel,ja,2016-03-13 00:00:00,27432,2016-03-19 13:16:57
49507,2016-03-16 17:38:32,BMW_528i_E39_Schaltgetriebe_Unfall,0,control,limousine,1998,manuell,193,5er,150000,0,NaN,bmw,ja,2016-03-16 00:00:00,25541,2016-03-30 08:47:38
49525,2016-03-09 17:59:02,Bmw_e36_318_i_Limo_Ringtool_PS_Tuning,0,test,NaN,2000,NaN,160,3er,150000,0,NaN,bmw,NaN,2016-03-09 00:00:00,66822,2016-03-15 04:45:26
49538,2016-03-14 10:55:27,Golf_3_mit_Tuev_.....PREISWERT!!!!,0,control,limousine,1998,manuell,60,golf,150000,0,benzin,volkswagen,nein,2016-03-14 00:00:00,15345,2016-03-14 10:55:27
49551,2016-03-16 23:40:18,Golf_IV_an_Bastler_zuverkaufen__reserviert_,0,test,NaN,2016,manuell,0,NaN,150000,6,diesel,volkswagen,nein,2016-03-16 00:00:00,4275,2016-03-16 23:40:18
49614,2016-03-09 17:49:39,Verkauf_meine__Audi__A3_.Gegen_tauschen_mit_Di...,0,test,NaN,2016,manuell,101,a3,150000,0,benzin,audi,nein,2016-03-09 00:00:00,47051,2016-03-10 14:15:53
49739,2016-03-17 15:47:34,Reparaturfaelligen_twingo,0,test,NaN,2016,manuell,58,twingo,150000,0,benzin,renault,nein,2016-03-17 00:00:00,27412,2016-03-17 15:47:34
49755,2016-04-02 13:46:23,Mercedes_Benz_w202_unfaller,0,test,limousine,1998,manuell,136,c_klasse,150000,7,benzin,mercedes_benz,NaN,2016-04-02 00:00:00,99441,2016-04-02 13:46:23
49793,2016-03-05 14:58:49,verkaufe_BMW_E_39,0,control,kombi,2000,automatik,183,5er,150000,1,benzin,bmw,NaN,2016-03-05 00:00:00,13125,2016-03-05 18:47:14
49880,2016-03-30 08:52:57,E39_528i_an_Bastler,0,control,NaN,2017,manuell,193,5er,150000,4,NaN,bmw,ja,2016-03-30 00:00:00,65468,2016-04-07 01:15:27
49884,2016-03-11 13:55:30,Audi_a6_2.5l__Schnaeppchen_nur_heute,0,test,kombi,1999,manuell,150,a6,150000,11,diesel,audi,NaN,2016-03-11 00:00:00,27711,2016-03-12 03:17:08
49943,2016-03-16 20:46:08,Opel_astra,0,control,NaN,2016,manuell,101,astra,150000,8,benzin,opel,NaN,2016-03-16 00:00:00,89134,2016-03-17 19:44:20
49960,2016-03-25 22:51:55,Ford_KA_zu_verschenken_***Reserviert***,0,control,kleinwagen,1999,manuell,60,ka,150000,6,benzin,ford,NaN,2016-03-25 00:00:00,34355,2016-03-25 22:51:55
49974,2016-03-20 10:52:31,Golf_1_Cabrio_Tuev_Neu_viele_Extras_alles_eing...,0,control,cabrio,1983,manuell,70,golf,150000,2,benzin,volkswagen,nein,2016-03-20 00:00:00,8209,2016-03-27 19:48:16
49984,2016-03-31 22:48:48,Student_sucht_ein__Anfaengerauto___ab_2000_BJ_...,0,test,NaN,2000,NaN,0,NaN,150000,0,NaN,sonstige_autos,NaN,2016-03-31 00:00:00,12103,2016-04-02 19:44:53

A few observations when examining price == 0 cars:
- In the name column we can see that some listings are 'suche' (= 'looking for'). This should be a separate category.
- It could be that people can bid on cars which are listed without price (or a very low price (1), see below).

For now, we are only interested in used cars being sold.

In [19]:
## showing cars with low price
autos[autos.price <= 10]

,date_crawled,name,price,abtest,vehicle_type,registration_year,gearbox,powerPS,model,odometer_km,registration_month,fuel_type,brand,unrepaired_damage,ad_created,postal_code,last_seen
27,2016-03-27 18:45:01,Hat_einer_Ahnung_mit_Ford_Galaxy_HILFE,0,control,NaN,2005,NaN,0,NaN,150000,0,NaN,ford,NaN,2016-03-27 00:00:00,66701,2016-03-27 18:45:01
55,2016-03-07 02:47:54,Mercedes_E320_AMG_zu_Tauschen!,1,test,NaN,2017,automatik,224,e_klasse,125000,7,benzin,mercedes_benz,nein,2016-03-06 00:00:00,22111,2016-03-08 05:45:44
71,2016-03-28 19:39:35,Suche_Opel_Astra_F__Corsa_oder_Kadett_E_mit_Re...,0,control,NaN,1990,manuell,0,NaN,5000,0,benzin,opel,NaN,2016-03-28 00:00:00,4552,2016-04-07 01:45:48
80,2016-03-09 15:57:57,Nissan_Primera_Hatchback_1_6_16v_73_Kw___99Ps_...,0,control,coupe,1999,manuell,99,primera,150000,3,benzin,nissan,ja,2016-03-09 00:00:00,66903,2016-03-09 16:43:50
87,2016-03-29 23:37:22,Bmw_520_e39_zum_ausschlachten,0,control,NaN,2000,NaN,0,5er,150000,0,NaN,bmw,NaN,2016-03-29 00:00:00,82256,2016-04-06 21:18:15
99,2016-04-05 09:48:54,Peugeot_207_CC___Cabrio_Bj_2011,0,control,cabrio,2011,manuell,0,2_reihe,60000,7,diesel,peugeot,nein,2016-04-05 00:00:00,99735,2016-04-07 12:17:34
118,2016-03-12 05:03:00,VW_Sharan_V6_204_PS_Karosse_Rohkarosse_mit_Pap...,0,control,bus,2001,manuell,204,sharan,150000,7,benzin,volkswagen,ja,2016-03-12 00:00:00,15370,2016-03-12 21:44:23
146,2016-03-22 23:59:28,Ford_Fiesta_rot,0,test,kleinwagen,1996,manuell,75,fiesta,20000,8,benzin,ford,NaN,2016-03-22 00:00:00,63069,2016-04-01 20:16:38
167,2016-04-02 19:43:45,Suche_VW_Multivan_Innenausstattung_Set_oder_TE...,0,control,NaN,2011,NaN,0,transporter,5000,0,NaN,volkswagen,NaN,2016-04-02 00:00:00,64739,2016-04-06 19:45:08
180,2016-03-19 10:50:25,Zu_verkaufen,0,test,NaN,2016,manuell,98,3_reihe,150000,12,benzin,mazda,ja,2016-03-19 00:00:00,30966,2016-03-24 03:17:21
226,2016-03-25 23:52:12,Porsche_911_S_Targa__67er_SWB,0,control,cabrio,1967,manuell,160,911,5000,12,benzin,porsche,nein,2016-03-25 00:00:00,44575,2016-04-05 14:46:39
234,2016-03-05 16:56:22,Fiat_Punto_Sport,0,control,NaN,2016,NaN,0,punto,150000,0,NaN,fiat,NaN,2016-03-05 00:00:00,44789,2016-03-17 22:47:09
248,2016-03-08 22:57:53,VW_Passat_zu_verkaufen,0,test,kombi,1998,manuell,0,passat,150000,10,benzin,volkswagen,ja,2016-03-08 00:00:00,34369,2016-03-29 16:16:18
259,2016-04-03 23:49:58,guenstiges_Auto_/_auch_defekt,0,control,NaN,2000,NaN,0,NaN,5000,6,NaN,sonstige_autos,NaN,2016-04-03 00:00:00,89269,2016-04-06 07:16:22
301,2016-03-08 20:37:59,Kaufe_alle_Autos_bietet_an,0,control,NaN,1990,NaN,0,NaN,5000,0,NaN,sonstige_autos,NaN,2016-03-08 00:00:00,13589,2016-04-05 18:44:43
323,2016-03-15 16:54:59,W220_Unfallfahrzeug,0,control,limousine,2001,automatik,224,s_klasse,150000,8,NaN,mercedes_benz,NaN,2016-03-15 00:00:00,45475,2016-04-06 12:44:20
327,2016-04-03 13:49:21,BMW_Cabrio_318i_/_BMW_318_tds_Touring,0,control,NaN,2016,manuell,90,3er,150000,2,diesel,bmw,NaN,2016-04-03 00:00:00,39112,2016-04-05 12:46:23
344,2016-03-22 11:25:18,Verkaufe_hier_mein_mein_schoener_honda_crx_in_...,1,test,NaN,2000,manuell,125,andere,5000,0,NaN,honda,NaN,2016-03-22 00:00:00,65391,2016-04-06 18:15:57
347,2016-04-02 11:48:02,Volvo_TP21__Sugga,0,test,suv,1956,NaN,0,andere,100000,0,NaN,volvo,NaN,2016-04-02 00:00:00,34414,2016-04-04 09:15:24
366,2016-03-21 20:36:25,Ford_Escort_Express_75__LKW_Zulussung___Diesel...,0,control,NaN,2000,NaN,0,andere,90000,0,diesel,ford,NaN,2016-03-21 00:00:00,3130,2016-03-28 19:16:45
389,2016-03-08 11:38:52,Vw_polo_classic,0,control,limousine,1999,manuell,75,NaN,150000,0,NaN,volkswagen,NaN,2016-03-08 00:00:00,14476,2016-03-14 09:16:30
418,2016-03-29 14:43:24,Fiat_SCUDO_8_Sitzer_Bus__Diesel_JTD__80_KW,0,test,bus,2003,manuell,80,andere,5000,5,diesel,fiat,nein,2016-03-29 00:00:00,35315,2016-04-05 23:47:14
427,2016-03-12 11:44:47,TOP_ZUSTAND_GrunePlakette_Euro4!!!,0,test,bus,2005,manuell,101,vivaro,80000,8,diesel,opel,nein,2016-03-12 00:00:00,93173,2016-03-12 11:44:47
430,2016-03-18 23:52:40,Winterraeder_FORD,0,test,NaN,2007,NaN,0,focus,5000,0,NaN,ford,NaN,2016-03-18 00:00:00,40549,2016-03-19 06:47:06
449,2016-04-03 20:59:59,Tausche_gegen_ein_smart.,0,test,limousine,2001,manuell,120,golf,150000,8,benzin,volkswagen,nein,2016-04-03 00:00:00,60439,2016-04-04 10:31:06
487,2016-03-14 21:41:36,MAG_MICH_KEINER_HABEN_Opel_Omega_B_Caravan_2.0...,0,test,kombi,1998,manuell,136,omega,150000,8,benzin,opel,ja,2016-03-14 00:00:00,59320,2016-03-17 11:48:08
502,2016-03-25 23:55:24,C32_AMG_C55_C43_w203,0,control,kombi,2001,NaN,354,c_klasse,150000,0,benzin,mercedes_benz,NaN,2016-03-25 00:00:00,79112,2016-03-26 08:40:35
519,2016-03-28 08:53:58,Verkaufe/Tausche_Seat_Inca__VW_Caddy__aus_2002...,0,test,andere,2002,manuell,64,andere,150000,2,diesel,seat,nein,2016-03-28 00:00:00,12627,2016-03-28 10:41:01
565,2016-03-20 20:49:36,Tausche_Audi_S3_8p_gegen_Golf_VI_Gti_mit_xenon,0,test,NaN,2016,manuell,330,NaN,150000,9,NaN,audi,nein,2016-03-20 00:00:00,97488,2016-03-22 00:44:53
593,2016-04-01 21:44:15,CLK_200__BRABUS_Optik,0,test,coupe,1998,manuell,136,clk,150000,1,benzin,mercedes_benz,NaN,2016-04-01 00:00:00,49191,2016-04-05 19:16:21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49043,2016-03-07 11:48:55,Opel_Vectra_B_Caravan,0,test,kombi,1997,manuell,101,NaN,150000,0,benzin,opel,NaN,2016-03-07 00:00:00,48429,2016-03-17 21:20:07
49082,2016-03-13 17:06:58,Passat_35i_b4_in_candy_weiss_original_lack,0,test,limousine,1996,manuell,90,NaN,150000,6,NaN,volkswagen,nein,2016-03-13 00:00:00,35799,2016-04-04 06:45:30
49240,2016-03-10 09:54:48,Suche_7_Sitzer_Espace_oder?_Biete_s.Beschreibung,1,test,kombi,1999,manuell,0,NaN,150000,4,benzin,bmw,NaN,2016-03-10 00:00:00,41199,2016-03-28 10:15:50
49254,2016-03-21 10:49:57,Corrado_G60_mit_2e_Motor,0,test,NaN,1995,manuell,0,NaN,150000,0,benzin,volkswagen,NaN,2016-03-21 00:00:00,53639,2016-03-22 15:18:35
49301,2016-03-20 20:52:40,Golf_3_Variant_Kombi_1.8,0,test,NaN,2000,NaN,0,NaN,150000,0,NaN,volkswagen,NaN,2016-03-20 00:00:00,4924,2016-03-30 15:17:15
49342,2016-03-09 20:47:01,Audi_80_b4_S_Color_und_BMW_318ti_compact_Tausc...,0,test,NaN,2017,manuell,90,80,150000,10,benzin,audi,ja,2016-03-09 00:00:00,25853,2016-03-11 17:45:36
49350,2016-03-19 23:57:15,Golf_II_Diesel,0,control,kleinwagen,1991,manuell,54,golf,150000,3,diesel,volkswagen,nein,2016-03-19 00:00:00,29664,2016-04-06 03:15:23
49377,2016-03-20 00:58:36,Tausche_BMW_318i_Facelift_Model_143_ps,1,control,limousine,2002,manuell,143,3er,150000,8,benzin,bmw,NaN,2016-03-19 00:00:00,86356,2016-03-20 04:56:34
49404,2016-04-04 03:03:16,Golf_2_BBS_LEDER_KW,0,control,limousine,1989,manuell,90,NaN,150000,3,NaN,volkswagen,nein,2016-04-04 00:00:00,52062,2016-04-06 08:45:25
49408,2016-03-30 20:57:06,OPEL_ASTRA,0,control,NaN,1995,manuell,60,astra,150000,0,benzin,opel,ja,2016-03-30 00:00:00,27711,2016-04-05 11:46:06
49479,2016-04-01 23:55:01,Tausch_mit_frischen_TÃœV,0,control,limousine,1995,manuell,101,a4,150000,5,benzin,audi,nein,2016-04-01 00:00:00,27753,2016-04-06 05:16:07
49496,2016-03-26 13:55:28,Bmw_e39_520,0,control,limousine,1998,manuell,0,NaN,5000,0,NaN,bmw,NaN,2016-03-26 00:00:00,26188,2016-03-26 13:55:28
49504,2016-03-13 19:42:57,Meriva_Lpg_1_6_16v,0,control,bus,2004,manuell,101,meriva,150000,10,lpg,opel,ja,2016-03-13 00:00:00,27432,2016-03-19 13:16:57
49507,2016-03-16 17:38:32,BMW_528i_E39_Schaltgetriebe_Unfall,0,control,limousine,1998,manuell,193,5er,150000,0,NaN,bmw,ja,2016-03-16 00:00:00,25541,2016-03-30 08:47:38
49525,2016-03-09 17:59:02,Bmw_e36_318_i_Limo_Ringtool_PS_Tuning,0,test,NaN,2000,NaN,160,3er,150000,0,NaN,bmw,NaN,2016-03-09 00:00:00,66822,2016-03-15 04:45:26
49528,2016-03-28 19:57:41,"BMW_E36__316i_Compact_M_Paket_""Schlachtfest""",1,control,NaN,2016,manuell,102,3er,150000,12,benzin,bmw,NaN,2016-03-28 00:00:00,49696,2016-04-07 02:47:04
49538,2016-03-14 10:55:27,Golf_3_mit_Tuev_.....PREISWERT!!!!,0,control,limousine,1998,manuell,60,golf,150000,0,benzin,volkswagen,nein,2016-03-14 00:00:00,15345,2016-03-14 10:55:27
49551,2016-03-16 23:40:18,Golf_IV_an_Bastler_zuverkaufen__reserviert_,0,test,NaN,2016,manuell,0,NaN,150000,6,diesel,volkswagen,nein,2016-03-16 00:00:00,4275,2016-03-16 23:40:18
49614,2016-03-09 17:49:39,Verkauf_meine__Audi__A3_.Gegen_tauschen_mit_Di...,0,test,NaN,2016,manuell,101,a3,150000,0,benzin,audi,nein,2016-03-09 00:00:00,47051,2016-03-10 14:15:53
49728,2016-03-25 16:00:11,Ford_Focus_1.4_16V_Bastlerauto,1,test,NaN,2016,manuell,0,focus,150000,0,benzin,ford,ja,2016-03-25 00:00:00,34587,2016-03-25 16:40:21
49739,2016-03-17 15:47:34,Reparaturfaelligen_twingo,0,test,NaN,2016,manuell,58,twingo,150000,0,benzin,renault,nein,2016-03-17 00:00:00,27412,2016-03-17 15:47:34
49755,2016-04-02 13:46:23,Mercedes_Benz_w202_unfaller,0,test,limousine,1998,manuell,136,c_klasse,150000,7,benzin,mercedes_benz,NaN,2016-04-02 00:00:00,99441,2016-04-02 13:46:23
49793,2016-03-05 14:58:49,verkaufe_BMW_E_39,0,control,kombi,2000,automatik,183,5er,150000,1,benzin,bmw,NaN,2016-03-05 00:00:00,13125,2016-03-05 18:47:14
49845,2016-03-21 00:50:15,Schlachte_VW_Sharan_vr6_Automatik___no_GTI_16V...,1,test,NaN,2000,automatik,174,sharan,5000,6,benzin,volkswagen,nein,2016-03-20 00:00:00,14621,2016-04-05 21:16:16
49880,2016-03-30 08:52:57,E39_528i_an_Bastler,0,control,NaN,2017,manuell,193,5er,150000,4,NaN,bmw,ja,2016-03-30 00:00:00,65468,2016-04-07 01:15:27
49884,2016-03-11 13:55:30,Audi_a6_2.5l__Schnaeppchen_nur_heute,0,test,kombi,1999,manuell,150,a6,150000,11,diesel,audi,NaN,2016-03-11 00:00:00,27711,2016-03-12 03:17:08
49943,2016-03-16 20:46:08,Opel_astra,0,control,NaN,2016,manuell,101,astra,150000,8,benzin,opel,NaN,2016-03-16 00:00:00,89134,2016-03-17 19:44:20
49960,2016-03-25 22:51:55,Ford_KA_zu_verschenken_***Reserviert***,0,control,kleinwagen,1999,manuell,60,ka,150000,6,benzin,ford,NaN,2016-03-25 00:00:00,34355,2016-03-25 22:51:55
49974,2016-03-20 10:52:31,Golf_1_Cabrio_Tuev_Neu_viele_Extras_alles_eing...,0,control,cabrio,1983,manuell,70,golf,150000,2,benzin,volkswagen,nein,2016-03-20 00:00:00,8209,2016-03-27 19:48:16
49984,2016-03-31 22:48:48,Student_sucht_ein__Anfaengerauto___ab_2000_BJ_...,0,test,NaN,2000,NaN,0,NaN,150000,0,NaN,sonstige_autos,NaN,2016-03-31 00:00:00,12103,2016-04-02 19:44:53

In [20]:
## splitting off 'suche' category 
suche = autos[autos['name'].str.contains("suche|Suche|SUCHE")]
## splitting off price=0 cars into separate price_0 df
price_0 = autos[autos.price <= 10]
## removing price=0 and suche cars from autos df
autos = autos[autos.price > 10]
autos = autos[~autos['name'].str.contains("suche|Suche|SUCHE")]

In [21]:
suche.describe()

,price,registration_year,powerPS,odometer_km,registration_month,postal_code
count,246.000000,246.000000,246.000000,246.000000,246.000000,246.000000
mean,2206.463415,1997.398374,28.654472,104329.268293,1.414634,43801.101626
std,9109.847358,34.469564,65.906230,61392.492038,2.974523,25346.041383
min,0.000000,1500.000000,0.000000,5000.000000,0.000000,1979.000000
25%,0.000000,1998.250000,0.000000,20000.000000,0.000000,26127.000000
50%,18.000000,2000.000000,0.000000,150000.000000,0.000000,40719.000000
75%,1875.000000,2005.000000,0.000000,150000.000000,1.000000,59348.000000
max,130000.000000,2019.000000,450.000000,150000.000000,12.000000,99974.000000

In [22]:
## determining odometer outliers threshold
autos['odometer_km'].value_counts()

150000    31224
125000     5037
100000     2099
90000      1731
80000      1414
70000      1215
60000      1154
50000      1010
40000       814
5000        791
30000       778
20000       756
10000       247
Name: odometer_km, dtype: int64

We can see that the number of car with 5000km doesn't really fit the descending count pattern. An explanation for this is that 5000 is the lowest category to choose from, so it includes 5000km and below.

In [23]:
## examining powerPS
autos['powerPS'].value_counts().head()

0      4817
75     3056
60     2129
150    1963
140    1862
Name: powerPS, dtype: int64

In [24]:
autos['powerPS'].sort_values().tail()

16743    14009
22592    15001
46986    16011
35039    16312
36421    17700
Name: powerPS, dtype: int64

We can see that the dataset contains cars with unrealistic horsepower values. The strongest car in the world has around 1300 horsepower, so we should drop anything above that.
Also, cars with 0 horsepower don't exist.

In [25]:
## dropping powerPS values above 1300
autos = autos[autos.powerPS <= 1300]
## dropping powerPS under 5 values 
autos = autos[autos.powerPS >= 5]

In [26]:
## registration years
autos['registration_year'].sort_values().tail()

49185    2019
27578    2800
22799    5000
27618    5911
49910    9000
Name: registration_year, dtype: int64

We can see that there are cars registered in the future in this dataset. We will remove these.

In [27]:
autos.sort_values(by='registration_year', ascending=False)

,date_crawled,name,price,abtest,vehicle_type,registration_year,gearbox,powerPS,model,odometer_km,registration_month,fuel_type,brand,unrepaired_damage,ad_created,postal_code,last_seen
49910,2016-04-03 21:39:15,Schoener_fast_neuer_Opel_Mokka_in_Zell_Mosel_m...,22200,test,NaN,9000,automatik,140,andere,10000,3,benzin,opel,NaN,2016-04-03 00:00:00,56856,2016-04-05 22:18:26
27618,2016-03-29 22:39:32,Golf_1_75ps_5911km_Original_Automatik_einer_de...,7999,test,NaN,5911,automatik,75,golf,10000,0,NaN,volkswagen,NaN,2016-03-29 00:00:00,41462,2016-04-06 09:17:09
22799,2016-03-20 18:56:44,Subaru_Impreza_GT,9000,test,NaN,5000,manuell,420,impreza,5000,6,benzin,subaru,nein,2016-03-20 00:00:00,34253,2016-04-07 02:45:30
27578,2016-03-31 22:49:04,VW_GOLF_2_SYNCRO,1700,test,NaN,2800,manuell,98,NaN,5000,7,benzin,volkswagen,NaN,2016-03-31 00:00:00,83022,2016-03-31 23:44:01
49185,2016-03-28 11:45:31,Alfa_Romeo_156_Sportwagon_1_8_T_Spark,1200,control,NaN,2019,manuell,140,156,150000,5,benzin,alfa_romeo,nein,2016-03-28 00:00:00,91058,2016-04-06 13:45:56
38617,2016-03-26 18:58:00,VW_Beetel_TÃœV_NEU__sehr_gepflegt_und_technisch...,2999,test,NaN,2018,manuell,125,beetle,150000,6,benzin,volkswagen,nein,2016-03-26 00:00:00,33803,2016-03-29 21:46:50
40254,2016-03-17 17:54:53,Mercedes_Benz_E_240,2799,control,NaN,2018,automatik,170,NaN,150000,8,NaN,mercedes_benz,NaN,2016-03-17 00:00:00,33790,2016-03-19 17:47:00
41266,2016-03-23 16:50:38,fiat_punto,4590,test,NaN,2018,manuell,78,punto,125000,6,benzin,fiat,nein,2016-03-23 00:00:00,50735,2016-04-05 20:47:00
43901,2016-03-27 15:52:30,Polo_6n2_1.4l,2599,control,NaN,2018,manuell,61,polo,40000,5,benzin,volkswagen,nein,2016-03-27 00:00:00,23560,2016-03-29 05:16:16
35047,2016-03-29 14:25:27,peugeot_206_tuev_neu_04.2018_mit_magnaflow_spo...,1300,test,NaN,2018,manuell,60,NaN,150000,3,benzin,peugeot,nein,2016-03-29 00:00:00,65197,2016-03-31 00:11:51
31664,2016-03-23 15:47:31,MERCEDES_GL350CDI,64900,test,NaN,2018,automatik,258,gl,30000,8,diesel,mercedes_benz,NaN,2016-03-23 00:00:00,72762,2016-04-05 18:44:55
13019,2016-03-23 16:47:32,A_140___1._Hd__nur_97tkm__TÃœV_neu__Sch_Heft__u...,3456,test,NaN,2018,manuell,82,a_klasse,100000,10,benzin,mercedes_benz,nein,2016-03-23 00:00:00,44229,2016-03-23 16:47:32
390,2016-03-25 12:59:06,Fiat_Bertone_X_1_9__X_1/9__X19__X_19__X1_9__X_19,7750,test,NaN,2018,manuell,76,andere,150000,6,benzin,fiat,nein,2016-03-25 00:00:00,78239,2016-03-28 12:16:50
49218,2016-04-01 19:48:06,Ford_Fiesta_1.3_4/5_Tuerer_16_Monate_Tuev,2750,control,NaN,2018,manuell,60,fiesta,125000,4,benzin,ford,nein,2016-04-01 00:00:00,58089,2016-04-05 16:45:21
8882,2016-03-15 15:54:39,Volvo_C30_1.6D_130294km__TÃœV_bis_02.2018___Leder,5300,control,NaN,2018,manuell,109,c_reihe,150000,6,diesel,volvo,nein,2016-03-15 00:00:00,16949,2016-03-29 21:45:42
22969,2016-03-23 18:51:17,Mercedes_A160_Avangarde_**TÃœV_Neu**,1750,test,NaN,2018,manuell,102,a_klasse,150000,8,benzin,mercedes_benz,nein,2016-03-23 00:00:00,72762,2016-04-02 01:18:50
40375,2016-04-04 17:50:07,Opel_Corsa_D_OPC,7599,test,NaN,2018,manuell,192,corsa,150000,10,benzin,opel,nein,2016-04-04 00:00:00,58300,2016-04-06 19:48:02
23314,2016-03-26 22:38:19,Gepflegter_VW_Touran_1.9TDI_Standheizung_Klima...,5999,test,NaN,2018,manuell,105,touran,150000,5,diesel,volkswagen,nein,2016-03-26 00:00:00,7768,2016-04-06 16:16:36
18345,2016-03-11 09:50:36,Mitsubischi_colt_zc3_tuev_2/18_anfaenger_auto,2100,control,NaN,2018,manuell,95,colt,150000,9,NaN,mitsubishi,nein,2016-03-11 00:00:00,34121,2016-03-28 16:47:01
15475,2016-03-29 16:56:14,Ford_Galaxy_1.9_TDI_Top!!!,3999,control,NaN,2018,manuell,115,galaxy,150000,7,NaN,ford,nein,2016-03-29 00:00:00,8468,2016-04-06 02:45:14
20620,2016-04-05 01:50:30,___Opel_Astra_Kombi_1.7_CDTI___TÃœV_bis_01.2018___,5999,control,NaN,2018,NaN,125,astra,150000,9,diesel,opel,NaN,2016-04-04 00:00:00,73312,2016-04-05 07:42:05
11239,2016-03-12 15:45:30,Ford_ka_mit_neu_tuev_und_Klima,899,control,NaN,2018,manuell,60,ka,150000,11,benzin,ford,nein,2016-03-12 00:00:00,6484,2016-03-18 03:43:22
45825,2016-03-20 16:56:24,Smart__mit_ATM_Motor,1300,test,NaN,2018,automatik,45,fortwo,125000,5,benzin,smart,nein,2016-03-20 00:00:00,48161,2016-04-06 22:47:13
35021,2016-03-15 00:53:06,Vw_Passat_1.6,1350,test,NaN,2018,manuell,101,passat,150000,6,NaN,volkswagen,nein,2016-03-14 00:00:00,33332,2016-03-15 07:44:05
13835,2016-03-24 10:56:32,Mercedes_E_200_Automatik_74060km_Tuev_neu,10990,test,NaN,2018,automatik,184,e_klasse,80000,0,benzin,mercedes_benz,NaN,2016-03-24 00:00:00,38820,2016-03-30 11:18:08
19626,2016-03-12 13:37:40,fahrbereiter_Seat_Ibiza,3200,control,NaN,2018,manuell,64,ibiza,100000,3,benzin,seat,nein,2016-03-12 00:00:00,6386,2016-03-12 13:37:40
33580,2016-03-25 10:50:40,BMW_e46_320td_Compact__8_fach_bereift__Tuev_bi...,2899,test,NaN,2018,manuell,150,3er,150000,1,diesel,bmw,nein,2016-03-25 00:00:00,94250,2016-04-06 10:45:02
26542,2016-03-08 21:54:46,Ford_Focus_Style__TÃœV_NEU__Klima__Tempomat,3750,control,NaN,2018,manuell,101,focus,150000,6,NaN,ford,NaN,2016-03-08 00:00:00,32791,2016-03-17 08:47:11
2785,2016-03-30 12:55:06,Seat_Leon,4999,control,NaN,2018,manuell,102,leon,100000,8,benzin,seat,NaN,2016-03-30 00:00:00,44147,2016-04-07 04:15:40
33738,2016-04-02 15:36:21,Gepflegter_Seat_Ibiza_in_weiss,5950,control,NaN,2018,manuell,70,ibiza,90000,11,benzin,seat,NaN,2016-04-02 00:00:00,45721,2016-04-06 14:15:58
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7094,2016-03-08 16:45:15,Borgward_isabella_restauration_Guenstiger_Oldt...,2460,test,limousine,1960,manuell,60,NaN,60000,3,benzin,sonstige_autos,nein,2016-03-08 00:00:00,72144,2016-03-09 15:47:46
1548,2016-03-25 14:46:44,1936_Daimler_Fifteen_Special_Projekt,7999,control,NaN,1960,NaN,65,NaN,150000,6,benzin,sonstige_autos,NaN,2016-03-25 00:00:00,50259,2016-04-06 17:46:36
36822,2016-03-16 08:56:42,Triumph_TR3_A,27900,test,cabrio,1960,manuell,101,NaN,80000,7,benzin,sonstige_autos,nein,2016-03-16 00:00:00,42653,2016-04-06 01:45:01
24291,2016-03-05 14:45:08,Ford_F_100,13999,control,andere,1959,manuell,240,NaN,70000,6,benzin,ford,NaN,2016-03-05 00:00:00,31275,2016-03-06 03:44:50
9620,2016-03-05 21:53:43,Sehr_schoener_Plymouth_Savoy,33000,test,limousine,1959,manuell,111,NaN,150000,1,benzin,sonstige_autos,NaN,2016-03-05 00:00:00,93133,2016-04-07 13:17:05
13366,2016-03-26 12:40:12,Andere_Panhard_PL_17,13900,control,limousine,1959,manuell,42,NaN,10000,5,benzin,sonstige_autos,nein,2016-03-26 00:00:00,79238,2016-04-05 23:46:49
20471,2016-03-28 13:38:56,Biete_312_Wartburg_Limousine__Baujahr_05/1959,5500,test,limousine,1959,manuell,60,NaN,5000,5,benzin,sonstige_autos,NaN,2016-03-28 00:00:00,7570,2016-04-06 16:46:34
23854,2016-03-28 12:59:22,Ford_Fairlane,17200,test,coupe,1959,automatik,230,andere,150000,7,benzin,ford,nein,2016-03-28 00:00:00,26789,2016-04-06 16:15:38
34541,2016-04-02 01:57:41,Mercedes_Benz_180_D_Ponton_mit_Faltdach,14900,test,limousine,1959,manuell,48,b_klasse,70000,7,diesel,mercedes_benz,nein,2016-04-02 00:00:00,38122,2016-04-06 04:45:19
10358,2016-03-19 13:45:25,Wartburg_311_zu_verkaufen,2300,test,limousine,1958,manuell,45,NaN,80000,1,benzin,sonstige_autos,NaN,2016-03-19 00:00:00,9600,2016-03-30 05:47:21
20105,2016-03-18 21:37:22,VW_Winker_Faltdach_Kaefer_Bj_1958_zum_Fertigst...,3800,control,limousine,1958,manuell,30,kaefer,150000,0,benzin,volkswagen,NaN,2016-03-18 00:00:00,25712,2016-03-18 21:37:22
23044,2016-03-20 15:54:00,Mercedes_Benz_Ponton_220s_mit_grossem_Faltdach...,25500,control,limousine,1957,manuell,100,andere,100000,0,benzin,mercedes_benz,NaN,2016-03-20 00:00:00,26209,2016-04-06 20:45:31
40077,2016-03-12 23:57:10,Andere_Horch_Sachsenring_P2M_Kuebelwagen_DDR_N...,22500,control,suv,1957,manuell,65,NaN,20000,7,benzin,sonstige_autos,nein,2016-03-12 00:00:00,1187,2016-04-02 12:47:49
7294,2016-03-28 16:26:34,YA126_DAF_Berge__Werstatt_und_Manschaft_Wagen,9990,test,suv,1956,manuell,75,NaN,20000,6,benzin,sonstige_autos,nein,2016-03-28 00:00:00,56206,2016-04-07 01:15:19
26570,2016-03-20 16:52:36,Opel_Olympia_Rekord,10800,test,limousine,1956,manuell,45,andere,100000,5,benzin,opel,nein,2016-03-20 00:00:00,36404,2016-04-06 22:47:17
19914,2016-03-06 10:51:30,Massey_Ferguson_MF35_FE35_Traktor_Trecker_Dies...,1300,test,andere,1956,manuell,34,NaN,10000,1,diesel,sonstige_autos,NaN,2016-03-06 00:00:00,46487,2016-03-13 02:16:32
36794,2016-04-01 09:47:52,Mercedes_Benz_190SL_FIN_Nr._63_top_History__In...,99900,test,cabrio,1955,manuell,105,andere,90000,6,NaN,mercedes_benz,nein,2016-04-01 00:00:00,74321,2016-04-07 06:17:29
25556,2016-03-29 11:47:24,Chevrolet_Belair_1954_/_Continental_Kit,11500,test,limousine,1954,NaN,150,andere,125000,6,benzin,chevrolet,nein,2016-03-29 00:00:00,72636,2016-04-05 20:47:15
40765,2016-03-07 12:52:18,Citroen_11_cv_BL_Traction_Avant,14999,test,andere,1954,manuell,54,NaN,100000,0,NaN,citroen,NaN,2016-03-07 00:00:00,47669,2016-04-06 03:16:32
44406,2016-03-15 14:47:26,Mercedes_Benz_170_S_Cabriolet_A__Startklar_fue...,120000,control,cabrio,1951,manuell,52,andere,20000,5,benzin,mercedes_benz,nein,2016-03-15 00:00:00,1067,2016-04-06 05:15:50
35921,2016-03-20 20:48:25,Land_Rover_Serie_I,25500,test,suv,1951,manuell,50,andere,40000,1,benzin,land_rover,nein,2016-03-20 00:00:00,76327,2016-04-07 05:45:28
14020,2016-03-19 11:52:47,Oldtimeraufloesung,10000,test,coupe,1950,manuell,130,andere,5000,1,benzin,alfa_romeo,nein,2016-03-19 00:00:00,34128,2016-04-06 14:46:35
25792,2016-03-09 10:54:11,Andere_GAZ_Oldtimergelaendewagen_1941,9500,control,suv,1941,manuell,57,NaN,40000,1,benzin,sonstige_autos,nein,2016-03-09 00:00:00,59557,2016-03-12 21:16:29
13963,2016-03-20 17:51:49,Mercedes_Benz_L1500S_Wehrmacht_/_Luftwaffe___F...,26900,test,andere,1941,manuell,60,andere,60000,7,benzin,mercedes_benz,nein,2016-03-20 00:00:00,38723,2016-04-07 01:17:51
21421,2016-03-05 17:45:32,Ford_Business_Coupe_Hotrod_Projekt.1937,7000,test,coupe,1937,manuell,85,andere,5000,8,benzin,ford,ja,2016-03-05 00:00:00,8359,2016-04-07 10:44:39
26607,2016-03-21 14:45:26,MG_Andere,25500,control,cabrio,1937,manuell,50,NaN,50000,5,benzin,sonstige_autos,nein,2016-03-21 00:00:00,53804,2016-04-06 11:17:17
23804,2016-03-30 22:42:50,Mercedes_Benz_170V,4800,control,limousine,1937,manuell,38,andere,5000,0,benzin,mercedes_benz,NaN,2016-03-30 00:00:00,23936,2016-03-30 22:42:50
11246,2016-03-26 19:49:59,Ford_Model_A_Roadster_Deluxe_1931,27500,control,cabrio,1931,manuell,39,andere,10000,7,benzin,ford,nein,2016-03-26 00:00:00,9322,2016-04-06 09:46:59
22101,2016-03-09 16:51:17,BMW_Andere,11500,test,cabrio,1929,manuell,15,andere,5000,1,NaN,bmw,ja,2016-03-09 00:00:00,70569,2016-04-07 06:17:11
21416,2016-03-12 08:36:21,Essex_super_six__Ford_A,16500,control,cabrio,1927,manuell,40,andere,5000,5,benzin,ford,NaN,2016-03-12 00:00:00,74821,2016-03-15 12:45:12

In [28]:
autos['registration_year'].sort_values().head()

21416    1927
22101    1929
11246    1931
21421    1937
26607    1937
Name: registration_year, dtype: int64

The oldest car in the set is from 1927, which on closer inspection turns out to be an oldtimer. We will keep these values.

Since the set was scraped in 2016, we will carefully inspect values between 2016 and 2019 (it could be that DataQuest added these observations to muddy the set).

In [29]:
autos.sort_values(by='registration_year', ascending=False)

,date_crawled,name,price,abtest,vehicle_type,registration_year,gearbox,powerPS,model,odometer_km,registration_month,fuel_type,brand,unrepaired_damage,ad_created,postal_code,last_seen
49910,2016-04-03 21:39:15,Schoener_fast_neuer_Opel_Mokka_in_Zell_Mosel_m...,22200,test,NaN,9000,automatik,140,andere,10000,3,benzin,opel,NaN,2016-04-03 00:00:00,56856,2016-04-05 22:18:26
27618,2016-03-29 22:39:32,Golf_1_75ps_5911km_Original_Automatik_einer_de...,7999,test,NaN,5911,automatik,75,golf,10000,0,NaN,volkswagen,NaN,2016-03-29 00:00:00,41462,2016-04-06 09:17:09
22799,2016-03-20 18:56:44,Subaru_Impreza_GT,9000,test,NaN,5000,manuell,420,impreza,5000,6,benzin,subaru,nein,2016-03-20 00:00:00,34253,2016-04-07 02:45:30
27578,2016-03-31 22:49:04,VW_GOLF_2_SYNCRO,1700,test,NaN,2800,manuell,98,NaN,5000,7,benzin,volkswagen,NaN,2016-03-31 00:00:00,83022,2016-03-31 23:44:01
49185,2016-03-28 11:45:31,Alfa_Romeo_156_Sportwagon_1_8_T_Spark,1200,control,NaN,2019,manuell,140,156,150000,5,benzin,alfa_romeo,nein,2016-03-28 00:00:00,91058,2016-04-06 13:45:56
38617,2016-03-26 18:58:00,VW_Beetel_TÃœV_NEU__sehr_gepflegt_und_technisch...,2999,test,NaN,2018,manuell,125,beetle,150000,6,benzin,volkswagen,nein,2016-03-26 00:00:00,33803,2016-03-29 21:46:50
40254,2016-03-17 17:54:53,Mercedes_Benz_E_240,2799,control,NaN,2018,automatik,170,NaN,150000,8,NaN,mercedes_benz,NaN,2016-03-17 00:00:00,33790,2016-03-19 17:47:00
41266,2016-03-23 16:50:38,fiat_punto,4590,test,NaN,2018,manuell,78,punto,125000,6,benzin,fiat,nein,2016-03-23 00:00:00,50735,2016-04-05 20:47:00
43901,2016-03-27 15:52:30,Polo_6n2_1.4l,2599,control,NaN,2018,manuell,61,polo,40000,5,benzin,volkswagen,nein,2016-03-27 00:00:00,23560,2016-03-29 05:16:16
35047,2016-03-29 14:25:27,peugeot_206_tuev_neu_04.2018_mit_magnaflow_spo...,1300,test,NaN,2018,manuell,60,NaN,150000,3,benzin,peugeot,nein,2016-03-29 00:00:00,65197,2016-03-31 00:11:51
31664,2016-03-23 15:47:31,MERCEDES_GL350CDI,64900,test,NaN,2018,automatik,258,gl,30000,8,diesel,mercedes_benz,NaN,2016-03-23 00:00:00,72762,2016-04-05 18:44:55
13019,2016-03-23 16:47:32,A_140___1._Hd__nur_97tkm__TÃœV_neu__Sch_Heft__u...,3456,test,NaN,2018,manuell,82,a_klasse,100000,10,benzin,mercedes_benz,nein,2016-03-23 00:00:00,44229,2016-03-23 16:47:32
390,2016-03-25 12:59:06,Fiat_Bertone_X_1_9__X_1/9__X19__X_19__X1_9__X_19,7750,test,NaN,2018,manuell,76,andere,150000,6,benzin,fiat,nein,2016-03-25 00:00:00,78239,2016-03-28 12:16:50
49218,2016-04-01 19:48:06,Ford_Fiesta_1.3_4/5_Tuerer_16_Monate_Tuev,2750,control,NaN,2018,manuell,60,fiesta,125000,4,benzin,ford,nein,2016-04-01 00:00:00,58089,2016-04-05 16:45:21
8882,2016-03-15 15:54:39,Volvo_C30_1.6D_130294km__TÃœV_bis_02.2018___Leder,5300,control,NaN,2018,manuell,109,c_reihe,150000,6,diesel,volvo,nein,2016-03-15 00:00:00,16949,2016-03-29 21:45:42
22969,2016-03-23 18:51:17,Mercedes_A160_Avangarde_**TÃœV_Neu**,1750,test,NaN,2018,manuell,102,a_klasse,150000,8,benzin,mercedes_benz,nein,2016-03-23 00:00:00,72762,2016-04-02 01:18:50
40375,2016-04-04 17:50:07,Opel_Corsa_D_OPC,7599,test,NaN,2018,manuell,192,corsa,150000,10,benzin,opel,nein,2016-04-04 00:00:00,58300,2016-04-06 19:48:02
23314,2016-03-26 22:38:19,Gepflegter_VW_Touran_1.9TDI_Standheizung_Klima...,5999,test,NaN,2018,manuell,105,touran,150000,5,diesel,volkswagen,nein,2016-03-26 00:00:00,7768,2016-04-06 16:16:36
18345,2016-03-11 09:50:36,Mitsubischi_colt_zc3_tuev_2/18_anfaenger_auto,2100,control,NaN,2018,manuell,95,colt,150000,9,NaN,mitsubishi,nein,2016-03-11 00:00:00,34121,2016-03-28 16:47:01
15475,2016-03-29 16:56:14,Ford_Galaxy_1.9_TDI_Top!!!,3999,control,NaN,2018,manuell,115,galaxy,150000,7,NaN,ford,nein,2016-03-29 00:00:00,8468,2016-04-06 02:45:14
20620,2016-04-05 01:50:30,___Opel_Astra_Kombi_1.7_CDTI___TÃœV_bis_01.2018___,5999,control,NaN,2018,NaN,125,astra,150000,9,diesel,opel,NaN,2016-04-04 00:00:00,73312,2016-04-05 07:42:05
11239,2016-03-12 15:45:30,Ford_ka_mit_neu_tuev_und_Klima,899,control,NaN,2018,manuell,60,ka,150000,11,benzin,ford,nein,2016-03-12 00:00:00,6484,2016-03-18 03:43:22
45825,2016-03-20 16:56:24,Smart__mit_ATM_Motor,1300,test,NaN,2018,automatik,45,fortwo,125000,5,benzin,smart,nein,2016-03-20 00:00:00,48161,2016-04-06 22:47:13
35021,2016-03-15 00:53:06,Vw_Passat_1.6,1350,test,NaN,2018,manuell,101,passat,150000,6,NaN,volkswagen,nein,2016-03-14 00:00:00,33332,2016-03-15 07:44:05
13835,2016-03-24 10:56:32,Mercedes_E_200_Automatik_74060km_Tuev_neu,10990,test,NaN,2018,automatik,184,e_klasse,80000,0,benzin,mercedes_benz,NaN,2016-03-24 00:00:00,38820,2016-03-30 11:18:08
19626,2016-03-12 13:37:40,fahrbereiter_Seat_Ibiza,3200,control,NaN,2018,manuell,64,ibiza,100000,3,benzin,seat,nein,2016-03-12 00:00:00,6386,2016-03-12 13:37:40
33580,2016-03-25 10:50:40,BMW_e46_320td_Compact__8_fach_bereift__Tuev_bi...,2899,test,NaN,2018,manuell,150,3er,150000,1,diesel,bmw,nein,2016-03-25 00:00:00,94250,2016-04-06 10:45:02
26542,2016-03-08 21:54:46,Ford_Focus_Style__TÃœV_NEU__Klima__Tempomat,3750,control,NaN,2018,manuell,101,focus,150000,6,NaN,ford,NaN,2016-03-08 00:00:00,32791,2016-03-17 08:47:11
2785,2016-03-30 12:55:06,Seat_Leon,4999,control,NaN,2018,manuell,102,leon,100000,8,benzin,seat,NaN,2016-03-30 00:00:00,44147,2016-04-07 04:15:40
33738,2016-04-02 15:36:21,Gepflegter_Seat_Ibiza_in_weiss,5950,control,NaN,2018,manuell,70,ibiza,90000,11,benzin,seat,NaN,2016-04-02 00:00:00,45721,2016-04-06 14:15:58
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7094,2016-03-08 16:45:15,Borgward_isabella_restauration_Guenstiger_Oldt...,2460,test,limousine,1960,manuell,60,NaN,60000,3,benzin,sonstige_autos,nein,2016-03-08 00:00:00,72144,2016-03-09 15:47:46
1548,2016-03-25 14:46:44,1936_Daimler_Fifteen_Special_Projekt,7999,control,NaN,1960,NaN,65,NaN,150000,6,benzin,sonstige_autos,NaN,2016-03-25 00:00:00,50259,2016-04-06 17:46:36
36822,2016-03-16 08:56:42,Triumph_TR3_A,27900,test,cabrio,1960,manuell,101,NaN,80000,7,benzin,sonstige_autos,nein,2016-03-16 00:00:00,42653,2016-04-06 01:45:01
24291,2016-03-05 14:45:08,Ford_F_100,13999,control,andere,1959,manuell,240,NaN,70000,6,benzin,ford,NaN,2016-03-05 00:00:00,31275,2016-03-06 03:44:50
9620,2016-03-05 21:53:43,Sehr_schoener_Plymouth_Savoy,33000,test,limousine,1959,manuell,111,NaN,150000,1,benzin,sonstige_autos,NaN,2016-03-05 00:00:00,93133,2016-04-07 13:17:05
13366,2016-03-26 12:40:12,Andere_Panhard_PL_17,13900,control,limousine,1959,manuell,42,NaN,10000,5,benzin,sonstige_autos,nein,2016-03-26 00:00:00,79238,2016-04-05 23:46:49
20471,2016-03-28 13:38:56,Biete_312_Wartburg_Limousine__Baujahr_05/1959,5500,test,limousine,1959,manuell,60,NaN,5000,5,benzin,sonstige_autos,NaN,2016-03-28 00:00:00,7570,2016-04-06 16:46:34
23854,2016-03-28 12:59:22,Ford_Fairlane,17200,test,coupe,1959,automatik,230,andere,150000,7,benzin,ford,nein,2016-03-28 00:00:00,26789,2016-04-06 16:15:38
34541,2016-04-02 01:57:41,Mercedes_Benz_180_D_Ponton_mit_Faltdach,14900,test,limousine,1959,manuell,48,b_klasse,70000,7,diesel,mercedes_benz,nein,2016-04-02 00:00:00,38122,2016-04-06 04:45:19
10358,2016-03-19 13:45:25,Wartburg_311_zu_verkaufen,2300,test,limousine,1958,manuell,45,NaN,80000,1,benzin,sonstige_autos,NaN,2016-03-19 00:00:00,9600,2016-03-30 05:47:21
20105,2016-03-18 21:37:22,VW_Winker_Faltdach_Kaefer_Bj_1958_zum_Fertigst...,3800,control,limousine,1958,manuell,30,kaefer,150000,0,benzin,volkswagen,NaN,2016-03-18 00:00:00,25712,2016-03-18 21:37:22
23044,2016-03-20 15:54:00,Mercedes_Benz_Ponton_220s_mit_grossem_Faltdach...,25500,control,limousine,1957,manuell,100,andere,100000,0,benzin,mercedes_benz,NaN,2016-03-20 00:00:00,26209,2016-04-06 20:45:31
40077,2016-03-12 23:57:10,Andere_Horch_Sachsenring_P2M_Kuebelwagen_DDR_N...,22500,control,suv,1957,manuell,65,NaN,20000,7,benzin,sonstige_autos,nein,2016-03-12 00:00:00,1187,2016-04-02 12:47:49
7294,2016-03-28 16:26:34,YA126_DAF_Berge__Werstatt_und_Manschaft_Wagen,9990,test,suv,1956,manuell,75,NaN,20000,6,benzin,sonstige_autos,nein,2016-03-28 00:00:00,56206,2016-04-07 01:15:19
26570,2016-03-20 16:52:36,Opel_Olympia_Rekord,10800,test,limousine,1956,manuell,45,andere,100000,5,benzin,opel,nein,2016-03-20 00:00:00,36404,2016-04-06 22:47:17
19914,2016-03-06 10:51:30,Massey_Ferguson_MF35_FE35_Traktor_Trecker_Dies...,1300,test,andere,1956,manuell,34,NaN,10000,1,diesel,sonstige_autos,NaN,2016-03-06 00:00:00,46487,2016-03-13 02:16:32
36794,2016-04-01 09:47:52,Mercedes_Benz_190SL_FIN_Nr._63_top_History__In...,99900,test,cabrio,1955,manuell,105,andere,90000,6,NaN,mercedes_benz,nein,2016-04-01 00:00:00,74321,2016-04-07 06:17:29
25556,2016-03-29 11:47:24,Chevrolet_Belair_1954_/_Continental_Kit,11500,test,limousine,1954,NaN,150,andere,125000,6,benzin,chevrolet,nein,2016-03-29 00:00:00,72636,2016-04-05 20:47:15
40765,2016-03-07 12:52:18,Citroen_11_cv_BL_Traction_Avant,14999,test,andere,1954,manuell,54,NaN,100000,0,NaN,citroen,NaN,2016-03-07 00:00:00,47669,2016-04-06 03:16:32
44406,2016-03-15 14:47:26,Mercedes_Benz_170_S_Cabriolet_A__Startklar_fue...,120000,control,cabrio,1951,manuell,52,andere,20000,5,benzin,mercedes_benz,nein,2016-03-15 00:00:00,1067,2016-04-06 05:15:50
35921,2016-03-20 20:48:25,Land_Rover_Serie_I,25500,test,suv,1951,manuell,50,andere,40000,1,benzin,land_rover,nein,2016-03-20 00:00:00,76327,2016-04-07 05:45:28
14020,2016-03-19 11:52:47,Oldtimeraufloesung,10000,test,coupe,1950,manuell,130,andere,5000,1,benzin,alfa_romeo,nein,2016-03-19 00:00:00,34128,2016-04-06 14:46:35
25792,2016-03-09 10:54:11,Andere_GAZ_Oldtimergelaendewagen_1941,9500,control,suv,1941,manuell,57,NaN,40000,1,benzin,sonstige_autos,nein,2016-03-09 00:00:00,59557,2016-03-12 21:16:29
13963,2016-03-20 17:51:49,Mercedes_Benz_L1500S_Wehrmacht_/_Luftwaffe___F...,26900,test,andere,1941,manuell,60,andere,60000,7,benzin,mercedes_benz,nein,2016-03-20 00:00:00,38723,2016-04-07 01:17:51
21421,2016-03-05 17:45:32,Ford_Business_Coupe_Hotrod_Projekt.1937,7000,test,coupe,1937,manuell,85,andere,5000,8,benzin,ford,ja,2016-03-05 00:00:00,8359,2016-04-07 10:44:39
26607,2016-03-21 14:45:26,MG_Andere,25500,control,cabrio,1937,manuell,50,NaN,50000,5,benzin,sonstige_autos,nein,2016-03-21 00:00:00,53804,2016-04-06 11:17:17
23804,2016-03-30 22:42:50,Mercedes_Benz_170V,4800,control,limousine,1937,manuell,38,andere,5000,0,benzin,mercedes_benz,NaN,2016-03-30 00:00:00,23936,2016-03-30 22:42:50
11246,2016-03-26 19:49:59,Ford_Model_A_Roadster_Deluxe_1931,27500,control,cabrio,1931,manuell,39,andere,10000,7,benzin,ford,nein,2016-03-26 00:00:00,9322,2016-04-06 09:46:59
22101,2016-03-09 16:51:17,BMW_Andere,11500,test,cabrio,1929,manuell,15,andere,5000,1,NaN,bmw,ja,2016-03-09 00:00:00,70569,2016-04-07 06:17:11
21416,2016-03-12 08:36:21,Essex_super_six__Ford_A,16500,control,cabrio,1927,manuell,40,andere,5000,5,benzin,ford,NaN,2016-03-12 00:00:00,74821,2016-03-15 12:45:12

We can see that the cars with registration year 2018 have their ad created in 2016, which means that the registration years are wrong. The rest of the values for these cars seem legit, so we could either change these values into NaN (missing / null) values, or drop them.

Since it is only about 1500 observations, we drop these as well.

In [31]:
autos = autos[autos.registration_year < 2017]

When examining 'registration_month' we can see that there are a lot of '0' values. We could drop these, but it would mean a high loss of data (almost 2500 observations). Since we are not planning on using 'registration month' for analysis, let's not drop these values. We can interpret '0' here as 'don't know which month in this year'.

In [39]:
autos['registration_month'].value_counts()

3     4495
6     3800
4     3640
5     3628
7     3438
10    3269
9     3021
11    2977
12    2975
1     2867
8     2782
2     2663
0     2457
Name: registration_month, dtype: int64

In [42]:
## investigate model
autos['model'].value_counts()

golf                  3407
andere                2979
3er                   2433
polo                  1420
corsa                 1396
passat                1237
astra                 1226
a4                    1156
5er                   1068
c_klasse              1055
e_klasse               874
a3                     759
a6                     751
focus                  698
fiesta                 635
transporter            611
2_reihe                559
twingo                 509
1er                    507
a_klasse               489
fortwo                 488
vectra                 472
mondeo                 444
3_reihe                432
clio                   416
touran                 388
punto                  368
zafira                 348
ibiza                  304
octavia                292
                      ...
range_rover_sport       10
mii                     10
300c                    10
sirion                  10
lanos                    9
gl                       9
range_rover              9
r19                      8
90                       8
terios                   8
move                     7
lybra                    7
nubira                   6
exeo                     6
amarok                   6
crossfire                6
delta                    5
9000                     5
range_rover_evoque       5
lodgy                    5
croma                    4
v60                      3
materia                  3
145                      2
charade                  2
kappa                    2
200                      1
samara                   1
b_max                    1
rangerover               1
Name: model, Length: 243, dtype: int64

Observations:
- 'andere' (translates to 'other') is the second largest category in models. We could examine what kind of cars these are (see below). It turns out to be a mix of rare cars and regular ones. It will be hard to split this category.
- A lot of the models have similar namings but different: range_rover, range_rover_evoque. 3_reihe, 3er. Etcetera. It will be hard to group these models.

In [48]:
autos[autos.model == 'andere']

,date_crawled,name,price,abtest,vehicle_type,registration_year,gearbox,powerPS,model,odometer_km,registration_month,fuel_type,brand,unrepaired_damage,ad_created,postal_code,last_seen
0,2016-03-26 17:47:46,Peugeot_807_160_NAVTECH_ON_BOARD,5000,control,bus,2004,manuell,158,andere,150000,3,lpg,peugeot,nein,2016-03-26 00:00:00,79588,2016-04-06 06:45:54
19,2016-03-17 13:36:21,mazda_tribute_2.0_mit_gas_und_tuev_neu_2018,4150,control,suv,2004,manuell,124,andere,150000,2,lpg,mazda,nein,2016-03-17 00:00:00,40878,2016-03-17 14:45:58
45,2016-03-12 17:39:55,Toyota_Starlet_1.3,1000,test,kleinwagen,1995,manuell,75,andere,150000,3,benzin,toyota,nein,2016-03-12 00:00:00,74597,2016-04-07 08:45:19
70,2016-03-16 13:49:00,Saab_9_3_2.0i_Cabrio_SE,1750,control,cabrio,1999,manuell,131,andere,150000,4,benzin,saab,nein,2016-03-16 00:00:00,81829,2016-03-16 13:49:00
75,2016-04-02 18:52:03,Volvo_960/964_Limousine_6_Zylinder,3800,control,limousine,1990,automatik,204,andere,150000,8,benzin,volvo,nein,2016-04-02 00:00:00,92721,2016-04-06 18:47:41
95,2016-03-30 15:59:17,Jaguar_XJ_5.0_V8_Portfolio,36000,test,limousine,2012,automatik,385,andere,40000,8,benzin,jaguar,nein,2016-03-30 00:00:00,21720,2016-04-07 06:44:54
97,2016-04-01 16:54:40,Treuer_Begleiter_abzugeben,800,control,bus,2000,manuell,63,andere,125000,8,benzin,mazda,ja,2016-04-01 00:00:00,87648,2016-04-05 12:17:40
136,2016-04-03 18:57:17,2_mal_Subaru_Libero_super_delux,1499,control,bus,1995,manuell,54,andere,150000,8,benzin,subaru,ja,2016-04-03 00:00:00,56072,2016-04-07 11:15:22
149,2016-03-12 13:51:26,Kia_Sephia_GTX,550,control,limousine,1997,manuell,80,andere,100000,2,benzin,kia,nein,2016-03-12 00:00:00,52391,2016-03-12 13:51:26
153,2016-03-24 10:52:19,Porsche_Porsche_968___Turbo_S_Optik__Speed_Lin...,31000,test,coupe,1992,manuell,239,andere,150000,3,benzin,porsche,nein,2016-03-24 00:00:00,63517,2016-04-07 01:46:56
162,2016-03-28 10:54:23,Fiat_Grande_Punto_1.4_16V_Sport,4900,control,kleinwagen,2009,manuell,95,andere,125000,9,benzin,fiat,nein,2016-03-28 00:00:00,50374,2016-04-06 13:44:51
163,2016-03-07 17:50:53,CitroÃ«n_Xsara_1.8i_SX,600,test,limousine,1997,manuell,90,andere,150000,9,benzin,citroen,ja,2016-03-07 00:00:00,78083,2016-03-13 04:46:05
166,2016-04-03 20:50:55,Mercedes_Benz_200/8,15000,test,limousine,1972,manuell,95,andere,80000,5,benzin,mercedes_benz,nein,2016-04-03 00:00:00,71032,2016-04-05 21:46:55
173,2016-03-14 14:47:01,Audi_S4_Avant_tiptronic,14000,control,kombi,2005,automatik,344,andere,150000,11,benzin,audi,nein,2016-03-14 00:00:00,36469,2016-04-05 17:22:19
195,2016-04-03 11:43:27,Fiat_Grande_Punto_1.4_16V_Sport,3300,control,kleinwagen,2006,manuell,95,andere,125000,12,benzin,fiat,nein,2016-04-03 00:00:00,40599,2016-04-07 12:45:00
200,2016-03-28 20:41:51,Corvette_C6_Grand_Sport_Cabrio_Schalter_EU_Mod...,56500,control,cabrio,2012,manuell,436,andere,30000,11,benzin,chevrolet,nein,2016-03-28 00:00:00,96129,2016-04-07 02:47:03
201,2016-03-20 10:50:58,Mazda_2_Klima_Tuev__bis_12/_16_4_El._Fensterheber,1600,control,limousine,2003,manuell,80,andere,125000,11,NaN,mazda,nein,2016-03-20 00:00:00,25451,2016-04-06 07:45:46
217,2016-03-25 14:54:53,PORSCHE_924S__11/1989,8900,control,coupe,1989,NaN,160,andere,150000,11,benzin,porsche,NaN,2016-03-25 00:00:00,45136,2016-04-06 18:18:44
241,2016-03-27 21:56:01,Hyundai_Accent_1.3i_GLS,1000,test,limousine,2002,manuell,75,andere,125000,7,benzin,hyundai,nein,2016-03-27 00:00:00,18528,2016-03-31 04:46:38
246,2016-03-11 06:37:33,Chevrolet_Pick_up,1200,test,suv,1973,automatik,250,andere,150000,3,benzin,chevrolet,nein,2016-03-11 00:00:00,95158,2016-03-11 22:16:02
249,2016-03-18 17:37:34,Dodge_Caliber_SXT_1.8_Benzin_Gas,5200,test,limousine,2007,manuell,150,andere,100000,0,lpg,chrysler,nein,2016-03-18 00:00:00,99441,2016-04-05 22:44:34
275,2016-03-07 18:41:56,Chrsyler_Neon_gepflegt_wegen_Neukauf_abzugeben,2000,control,limousine,2001,manuell,133,andere,100000,9,benzin,chrysler,nein,2016-03-07 00:00:00,45478,2016-03-08 10:44:31
313,2016-03-06 22:41:57,Kia_Clarus_1_8_SLX_116_PS,400,control,limousine,1998,manuell,116,andere,150000,8,benzin,kia,NaN,2016-03-06 00:00:00,6571,2016-04-07 02:44:49
408,2016-03-15 21:49:23,Mitsubishi_Space_Star_mit_AHK,699,control,kombi,2000,manuell,81,andere,150000,2,benzin,mitsubishi,nein,2016-03-15 00:00:00,29614,2016-03-16 20:21:44
446,2016-03-16 09:47:04,Suzuki_Baleno_Tuev_Neu,790,test,limousine,1995,manuell,84,andere,150000,6,benzin,suzuki,nein,2016-03-16 00:00:00,1594,2016-03-16 09:47:04
494,2016-04-02 14:45:48,Mazda_6__2.0Diesel,1200,test,kombi,2003,manuell,121,andere,150000,3,NaN,mazda,ja,2016-04-02 00:00:00,98527,2016-04-06 13:15:53
500,2016-03-08 16:38:34,Schicker_Cadillac_Escalade_EXT,13000,test,suv,2002,automatik,360,andere,125000,1,benzin,chevrolet,nein,2016-03-08 00:00:00,48465,2016-04-06 12:17:15
518,2016-03-28 16:38:38,Jaguar_XK_3.5_Coupe_TOP,22650,test,coupe,2007,automatik,258,andere,100000,9,benzin,jaguar,nein,2016-03-28 00:00:00,94051,2016-03-28 16:38:38
531,2016-04-04 16:55:12,Suzuki_Vitara,2500,test,suv,1994,manuell,80,andere,150000,9,benzin,suzuki,nein,2016-04-04 00:00:00,42859,2016-04-06 18:46:48
537,2016-03-22 14:25:25,Audi_Cabriolet_1.8___TOP_ZUSTAND,6490,control,cabrio,1998,manuell,125,andere,125000,4,benzin,audi,nein,2016-03-22 00:00:00,60437,2016-03-24 13:11:54
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49376,2016-04-01 09:45:43,Fiat_Barchetta_Cabrio,1400,test,cabrio,1999,manuell,131,andere,150000,5,benzin,fiat,NaN,2016-04-01 00:00:00,46147,2016-04-01 09:45:43
49396,2016-03-15 19:37:20,Mercedes_Benz_240,950,control,kombi,1998,automatik,170,andere,150000,11,benzin,mercedes_benz,nein,2016-03-15 00:00:00,97762,2016-03-24 09:18:08
49554,2016-03-19 14:45:42,CitroÃ«n_Xantia_Kombi_2.0_HDi_Millesime__AU.neu...,599,test,kombi,2001,manuell,109,andere,40000,6,diesel,citroen,nein,2016-03-19 00:00:00,29574,2016-03-21 19:19:06
49569,2016-04-07 13:36:20,Mitsubishi_L_300_KAT,2500,control,bus,1996,manuell,111,andere,150000,3,benzin,mitsubishi,nein,2016-04-07 00:00:00,67657,2016-04-07 13:36:20
49586,2016-03-07 01:37:01,Toyota_Carina_1.6,1490,control,kombi,1997,manuell,99,andere,150000,3,benzin,toyota,nein,2016-03-07 00:00:00,86453,2016-03-15 03:15:27
49621,2016-03-09 23:55:28,Chevrolet_Nubira_1.6_Kombi_SX,3500,test,kombi,2006,manuell,109,andere,125000,5,benzin,chevrolet,nein,2016-03-09 00:00:00,26802,2016-03-12 10:15:09
49624,2016-03-17 14:37:15,Mercedes_Benz_W126_Coupe__500_SEC_H_Zulassungs...,4500,control,coupe,1982,automatik,232,andere,150000,8,benzin,mercedes_benz,nein,2016-03-17 00:00:00,86152,2016-04-06 22:47:09
49633,2016-04-03 22:36:22,Renault_Wind_TCe_100_Night_and_Day,8990,control,cabrio,2011,manuell,102,andere,50000,8,benzin,renault,NaN,2016-04-03 00:00:00,26817,2016-04-06 01:45:13
49665,2016-03-21 00:58:38,Opel_Frontera_Sport_Mistral,650,test,suv,1995,manuell,116,andere,150000,6,benzin,opel,ja,2016-03-20 00:00:00,67468,2016-04-05 22:45:49
49667,2016-03-07 16:53:16,Mercedes_Benz_300_CE_24,3980,control,coupe,1991,automatik,220,andere,150000,1,benzin,mercedes_benz,nein,2016-03-07 00:00:00,29352,2016-03-13 00:17:53
49680,2016-04-03 11:47:08,Volvo_Kombi_GL_940_mit_tuev_und_evtl_einen_Hae...,1300,control,kombi,1992,manuell,130,andere,150000,7,benzin,volvo,NaN,2016-04-03 00:00:00,90449,2016-04-07 12:45:52
49684,2016-03-26 15:53:54,Peugeot_807_HDi_130_Premium_2_2Liter_Navi_AHK_...,3300,test,bus,2006,manuell,128,andere,150000,2,diesel,peugeot,nein,2016-03-26 00:00:00,57223,2016-03-26 15:53:54
49713,2016-03-22 08:51:10,Toyota_Carina_1600_GL_TA60,1500,control,NaN,1985,manuell,70,andere,150000,4,benzin,toyota,NaN,2016-03-22 00:00:00,94032,2016-04-03 18:46:52
49716,2016-03-13 17:36:57,Peugeot_Expert,10900,control,bus,2013,manuell,128,andere,80000,3,diesel,peugeot,nein,2016-03-13 00:00:00,38118,2016-04-06 17:46:31
49761,2016-03-17 19:41:33,Mercedes_W124__Youngtimer_bald_Oldtimer_,2150,control,limousine,1989,automatik,132,andere,150000,11,benzin,mercedes_benz,nein,2016-03-17 00:00:00,72070,2016-04-07 07:16:42
49764,2016-03-07 21:52:19,Toyota_Land_Cruiser_Jagt_Forst_Offroad_Winde_2...,9990,control,suv,1998,manuell,125,andere,150000,8,diesel,toyota,nein,2016-03-07 00:00:00,86420,2016-03-10 21:16:16
49791,2016-03-24 15:52:51,Toyota_IQ_1.0_Multidrive,5999,test,kleinwagen,2009,automatik,68,andere,90000,6,benzin,toyota,nein,2016-03-24 00:00:00,42929,2016-04-07 07:46:40
49805,2016-03-16 20:40:05,Chrysler_Stratus_2.5_LX,3750,control,cabrio,1999,automatik,163,andere,125000,7,benzin,chrysler,nein,2016-03-16 00:00:00,47198,2016-03-20 21:45:22
49855,2016-03-24 09:36:21,Porsche_Cayman_S_PDK__Chrono_Plus__Approved__P...,33500,control,coupe,2009,automatik,320,andere,90000,1,benzin,porsche,nein,2016-03-24 00:00:00,74321,2016-03-24 09:36:21
49879,2016-03-14 11:59:32,Tausche_meinen__Daimlerchrysler_Stratus_Cabrio...,2500,test,cabrio,2000,manuell,163,andere,150000,5,benzin,chrysler,NaN,2016-03-14 00:00:00,41836,2016-03-16 01:47:00
49882,2016-03-19 14:51:02,Fiat_Marea_1_8_16V_Tausch_moeglich.Auch_Diesel...,1000,test,limousine,1997,manuell,113,andere,125000,9,benzin,fiat,nein,2016-03-19 00:00:00,56112,2016-04-07 04:45:14
49885,2016-03-29 18:25:18,CitroÃ«n_Xsara_Picasso_1.8i,1300,test,bus,2000,manuell,111,andere,150000,7,benzin,citroen,nein,2016-03-29 00:00:00,65462,2016-03-30 10:42:39
49904,2016-03-21 23:52:28,Susuki_Baleno_TÃœV_3.2018_Optisch_und_technisch...,1000,test,kombi,2001,manuell,96,andere,150000,3,benzin,suzuki,NaN,2016-03-21 00:00:00,33330,2016-04-05 15:17:43
49906,2016-03-16 21:47:09,Nissan_Pickup,7500,control,suv,2005,manuell,133,andere,150000,1,diesel,nissan,nein,2016-03-16 00:00:00,7743,2016-03-23 10:17:26
49912,2016-03-29 12:50:10,Audi_S3_SCHIEBEDACH_NAVY,9500,test,limousine,2007,manuell,265,andere,150000,6,benzin,audi,nein,2016-03-29 00:00:00,63452,2016-03-29 12:50:10
49920,2016-03-28 13:57:03,Mazda_323_F,700,test,kleinwagen,2000,manuell,65,andere,150000,3,NaN,mazda,NaN,2016-03-28 00:00:00,36205,2016-04-06 17:46:01
49944,2016-03-15 17:48:16,SAAB_9_3__2_0t_SE__Automatik__Tempomat__Regens...,1000,control,limousine,2000,automatik,150,andere,150000,6,benzin,saab,nein,2016-03-15 00:00:00,4105,2016-04-02 17:17:12
49962,2016-03-14 17:57:15,Mitsubishi_Space_Star_1__3_L__Bj_2004_Standhei...,2200,test,limousine,2004,manuell,82,andere,150000,4,benzin,mitsubishi,ja,2016-03-14 00:00:00,45481,2016-03-15 13:45:08
49968,2016-04-01 17:49:15,Mercedes_Benz_190_D_2.5_Automatik,2100,test,limousine,1986,automatik,90,andere,150000,9,diesel,mercedes_benz,nein,2016-04-01 00:00:00,40227,2016-04-05 13:16:35
49992,2016-03-10 19:37:38,Fiat_Grande_Punto_1.4_T_Jet_16V_Sport,4800,control,kleinwagen,2009,manuell,120,andere,125000,9,lpg,fiat,nein,2016-03-10 00:00:00,68642,2016-03-13 01:44:51

Let's move on to the date values. They are currently string values and we need to convert them in order to analyse them further:

- date_crawled
- ad_created
- last_seen

These values have both date and time values in one string. We can examine the dates by selecting only the date characters (first 10).

In [55]:
## distribution of dates in percentages
autos['date_crawled'].str[:10].value_counts(normalize=True, dropna=False).sort_index(ascending=True)

2016-03-05    0.025374
2016-03-06    0.014282
2016-03-07    0.036394
2016-03-08    0.033348
2016-03-09    0.032895
2016-03-10    0.032300
2016-03-11    0.032110
2016-03-12    0.037180
2016-03-13    0.015829
2016-03-14    0.036656
2016-03-15    0.034157
2016-03-16    0.029206
2016-03-17    0.031467
2016-03-18    0.012830
2016-03-19    0.034419
2016-03-20    0.038513
2016-03-21    0.037180
2016-03-22    0.032538
2016-03-23    0.031658
2016-03-24    0.029492
2016-03-25    0.031729
2016-03-26    0.032348
2016-03-27    0.030706
2016-03-28    0.035133
2016-03-29    0.033800
2016-03-30    0.033705
2016-03-31    0.031872
2016-04-01    0.034014
2016-04-02    0.035609
2016-04-03    0.038989
2016-04-04    0.036823
2016-04-05    0.012996
2016-04-06    0.003071
2016-04-07    0.001381
Name: date_crawled, dtype: float64

The data has been crawled between March and April 2016.

In [117]:
autos['registration_year'].describe()

count    42012.000000
mean      2003.168857
std          6.836022
min       1927.000000
25%       1999.000000
50%       2003.000000
75%       2008.000000
max       2016.000000
Name: registration_year, dtype: float64

In [120]:
autos['unrepaired_damage'].value_counts(dropna=False)

nein    32091
NaN      5923
ja       3998
Name: unrepaired_damage, dtype: int64

The 'unrepaired_damage' column is a strange one. It includes more missing values than 'ja' (= yes) values. My hypothesis is that sellers rather not answer this question if they have unrepaired damage to the car, thus a large portion of the missing values should be 'ja'. However, we can't tell right now and dropping all the missing values would lead to 6000 datapoints being lost, which is too large.

### Aggregation

We can continue with aggregation by brand for analysis purposes.

In [60]:
autos['brand'].nunique()

40

There are 40 unique brands in the list. Below is the top 5.

In [90]:
autos['brand'].value_counts().head()

volkswagen       8912
bmw              4789
opel             4437
mercedes_benz    4058
audi             3758
Name: brand, dtype: int64

In [100]:
autos.groupby([autos.brand == 'volkswagen']).describe()

         price                                                          \
         count         mean          std   min     25%     50%     75%
brand
False  33100.0  6479.069456  9946.099028  11.0  1400.0  3500.0  7999.0
True    8912.0  5704.942662  6352.681745  30.0  1300.0  3300.0  7990.0

                registration_year                ...    registration_month  \
            max             count         mean   ...                   75%
brand                                            ...
False  350000.0           33100.0  2003.299698   ...                   9.0
True    64500.0            8912.0  2002.682899   ...                   9.0

            postal_code                                                        \
        max       count          mean           std     min      25%      50%
brand
False  12.0     33100.0  52086.994532  25634.195355  1067.0  31787.0  51379.0
True   12.0      8912.0  49911.689071  26032.807974  1067.0  28863.0  47877.0


            75%      max
brand
False  72622.00  99998.0
True   71680.75  99998.0

[2 rows x 48 columns]

Our quick analysis above shows some statistics for volkswagen cars compared to the rest of the brands:

- 8912 of the roughly 40000 cars are volkswagen
- The mean price is 5700 euro, which is lower than the mean price of other brands combined.

Next, we want to compare the volkswagen brand to other brands individually. Below we can find the mean values for the numerical columns for each brand aggregated.

In [116]:
autos.groupby([autos.brand]).mean().round(0).sort_values(by='price', ascending=False)

,price,registration_year,powerPS,odometer_km,registration_month,postal_code
brand,,,,,,
porsche,48705.0,2002.0,309.0,97814.0,6.0,57755.0
land_rover,19666.0,2004.0,157.0,118077.0,6.0,54139.0
sonstige_autos,14267.0,1995.0,183.0,94985.0,6.0,50771.0
jaguar,12195.0,2002.0,241.0,127077.0,6.0,53726.0
jeep,12037.0,2003.0,191.0,127806.0,7.0,54843.0
mini,10677.0,2008.0,132.0,88392.0,6.0,56452.0
audi,9742.0,2004.0,168.0,128604.0,6.0,55336.0
mercedes_benz,9011.0,2002.0,167.0,130678.0,6.0,52013.0
bmw,8617.0,2003.0,175.0,132509.0,6.0,55442.0
chevrolet,6697.0,2004.0,144.0,97489.0,6.0,48483.0
skoda,6651.0,2007.0,108.0,110097.0,6.0,49022.0
kia,6218.0,2007.0,122.0,112076.0,6.0,49865.0
dacia,6143.0,2011.0,89.0,82061.0,6.0,50770.0
volkswagen,5705.0,2003.0,107.0,128267.0,6.0,49912.0
hyundai,5605.0,2007.0,110.0,104733.0,6.0,49703.0
toyota,5298.0,2005.0,110.0,115801.0,6.0,53053.0
volvo,5177.0,2001.0,154.0,138397.0,6.0,47727.0
nissan,5142.0,2004.0,110.0,116968.0,6.0,46972.0
seat,4696.0,2005.0,101.0,120566.0,6.0,52472.0
mazda,4347.0,2003.0,119.0,124281.0,6.0,50443.0
honda,4300.0,2001.0,116.0,121701.0,6.0,47338.0
suzuki,4292.0,2004.0,89.0,108414.0,6.0,49983.0
alfa_romeo,4170.0,2002.0,146.0,131813.0,6.0,57383.0
subaru,4121.0,2000.0,143.0,125815.0,6.0,60097.0
citroen,3935.0,2005.0,97.0,118929.0,6.0,48419.0
ford,3925.0,2003.0,108.0,124258.0,6.0,50200.0
smart,3768.0,2006.0,63.0,98274.0,6.0,49863.0
chrysler,3632.0,2001.0,156.0,133469.0,6.0,49480.0
lancia,3590.0,2000.0,103.0,124419.0,5.0,59207.0
mitsubishi,3551.0,2002.0,115.0,125698.0,6.0,48303.0
saab,3376.0,2000.0,160.0,144028.0,6.0,52760.0
peugeot,3258.0,2004.0,101.0,126261.0,6.0,53613.0
opel,3162.0,2002.0,101.0,129194.0,6.0,50340.0
lada,3021.0,2000.0,76.0,85952.0,6.0,53308.0
fiat,2967.0,2004.0,80.0,116823.0,6.0,55510.0
renault,2661.0,2003.0,91.0,126958.0,6.0,48428.0
trabant,2014.0,1981.0,28.0,54875.0,4.0,30105.0
rover,1778.0,2000.0,112.0,136200.0,6.0,47360.0
daihatsu,1751.0,2003.0,68.0,117263.0,7.0,44467.0
daewoo,1072.0,2002.0,80.0,123962.0,6.0,46575.0

## Concluding remarks and possible next steps

This concludes this data cleaning project. This cleaned dataset can now be used for machine learning purposes, for example to predict the price for which you can sell your car, or to see if a car is listed on Ebay below it's market value.

Further calculations could be done if we could scrape data on when a car was sold (listing is removed from Ebay). With that data we could measure how long it takes for a car to be sold.

Another next step would be a deepdive into the damage column. Currently, it has a lot of missing values. It would be interesting to build a machine learning model to predict the values of 'unrepaired_damage', using the values we do have in this set.